/********************************************************************************
** Form generated from reading UI file 'MainWindow.ui'
**
** Created: Fri Apr 6 15:12:21 2012
**      by: Qt User Interface Compiler version 4.7.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QGridLayout>
#include <QtGui/QHBoxLayout>
#include <QtGui/QHeaderView>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QSplitter>
#include <QtGui/QTabWidget>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>
#include "InfoTreeWidget.h"
#include "PanelPointSet.h"
#include "PanelROI.h"
#include "PanelSurface.h"
#include "PanelTrack.h"
#include "PanelVolume.h"
#include "RenderView2D.h"
#include "RenderView3D.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionNewVolume;
    QAction *actionLoadVolume;
    QAction *actionSaveVolume;
    QAction *actionSaveVolumeAs;
    QAction *actionNavigate;
    QAction *actionMeasure;
    QAction *actionVoxelEdit;
    QAction *actionROIEdit;
    QAction *actionPointSetEdit;
    QAction *actionLoadDTIVolumes;
    QAction *actionLoadSurface;
    QAction *actionSaveSurface;
    QAction *actionSaveSurfaceAs;
    QAction *actionNewROI;
    QAction *actionLoadROI;
    QAction *actionSaveROI;
    QAction *actionSaveROIAs;
    QAction *actionNewPointSet;
    QAction *actionLoadPointSet;
    QAction *actionSavePointSet;
    QAction *actionSavePointSetAs;
    QAction *actionSaveScreenshot;
    QAction *actionSaveMovieFrames;
    QAction *actionExit;
    QAction *actionCopy;
    QAction *actionCopyStructure;
    QAction *actionPaste;
    QAction *actionUndo;
    QAction *actionRedo;
    QAction *actionRenameLayer;
    QAction *actionPreferences;
    QAction *actionLayout1x1;
    QAction *actionLayout2x2;
    QAction *actionLayout1n3;
    QAction *actionLayout1n3h;
    QAction *actionViewSagittal;
    QAction *actionViewCoronal;
    QAction *actionViewAxial;
    QAction *actionView3D;
    QAction *actionShowControlPanel;
    QAction *actionResetView;
    QAction *actionResetViewNearestAxis;
    QAction *actionShowCoordinateAnnotation;
    QAction *actionShowColorScale;
    QAction *actionShowSliceFrames;
    QAction *actionToggleCursorVisibility;
    QAction *actionToggleVoxelCoordinateDisplay;
    QAction *actionShowAllLayers;
    QAction *actionHideAllLayers;
    QAction *actionCycleLayer;
    QAction *actionReverseCycleLayer;
    QAction *actionToggleVolumeVisibility;
    QAction *actionToggleSurfaceVisibility;
    QAction *actionToggleROIVisibility;
    QAction *actionTogglePointSetVisibility;
    QAction *actionTransformVolume;
    QAction *actionCropVolume;
    QAction *actionCreateOptimalCombinedVolume;
    QAction *actionRepositionSurface;
    QAction *actionSavePoint;
    QAction *actionGoToPoint;
    QAction *actionShowLabelStats;
    QAction *actionQuickReference;
    QAction *actionAbout;
    QAction *actionVolumeFilterMean;
    QAction *actionVolumeFilterMedian;
    QAction *actionVolumeFilterConvolve;
    QAction *actionVolumeFilterGradient;
    QAction *actionCloseVolume;
    QAction *actionCloseSurface;
    QAction *actionCloseROI;
    QAction *actionClosePointSet;
    QAction *actionVolumes;
    QAction *actionSurfaces;
    QAction *actionVolumeFilterSobel;
    QAction *actionRunCommand;
    QAction *actionLoadCommand;
    QAction *actionShowCommandConsole;
    QAction *actionLoadTrack;
    QAction *actionCloseTrack;
    QAction *actionShowSlices;
    QAction *actionLoadTrackVolume;
    QAction *actionIncreaseOpacity;
    QAction *actionDecreaseOpacity;
    QAction *actionIntensityProject;
    QAction *actionTimeCourse;
    QAction *actionPlot;
    QWidget *centralWidget;
    QHBoxLayout *horizontalLayout;
    QSplitter *splitterMain;
    QTabWidget *tabWidgetControlPanel;
    PanelVolume *tabVolume;
    PanelSurface *tabSurface;
    PanelROI *tabROI;
    PanelPointSet *tabPointSet;
    PanelTrack *tabTrack;
    QWidget *widget;
    QHBoxLayout *horizontalLayout_2;
    QSplitter *splitterInfoPanel;
    QWidget *widgetViewportHolder;
    QGridLayout *gridLayoutViewport;
    RenderView2D *viewAxial;
    RenderView2D *viewSagittal;
    RenderView2D *viewCoronal;
    RenderView3D *view3D;
    QWidget *widget_3;
    QHBoxLayout *horizontalLayout_3;
    InfoTreeWidget *treeWidgetCursorInfo;
    InfoTreeWidget *treeWidgetMouseInfo;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menuRecentFiles;
    QMenu *menuEdit;
    QMenu *menuView;
    QMenu *menuViewport_Layout;
    QMenu *menuLayer;
    QMenu *menuAction;
    QMenu *menuTools;
    QMenu *menuVolume_Fiilter;
    QMenu *menuHelp;
    QToolBar *mainToolBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1213, 872);
        MainWindow->setIconSize(QSize(24, 24));
        MainWindow->setUnifiedTitleAndToolBarOnMac(false);
        actionNewVolume = new QAction(MainWindow);
        actionNewVolume->setObjectName(QString::fromUtf8("actionNewVolume"));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/resource/icons/volume_new.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionNewVolume->setIcon(icon);
        actionLoadVolume = new QAction(MainWindow);
        actionLoadVolume->setObjectName(QString::fromUtf8("actionLoadVolume"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/resource/icons/volume_load.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionLoadVolume->setIcon(icon1);
        actionSaveVolume = new QAction(MainWindow);
        actionSaveVolume->setObjectName(QString::fromUtf8("actionSaveVolume"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/resource/icons/volume_save.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSaveVolume->setIcon(icon2);
        actionSaveVolumeAs = new QAction(MainWindow);
        actionSaveVolumeAs->setObjectName(QString::fromUtf8("actionSaveVolumeAs"));
        actionNavigate = new QAction(MainWindow);
        actionNavigate->setObjectName(QString::fromUtf8("actionNavigate"));
        actionNavigate->setCheckable(true);
        actionNavigate->setChecked(true);
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/resource/icons/navigate.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionNavigate->setIcon(icon3);
        actionMeasure = new QAction(MainWindow);
        actionMeasure->setObjectName(QString::fromUtf8("actionMeasure"));
        actionMeasure->setCheckable(true);
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/resource/icons/measure.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionMeasure->setIcon(icon4);
        actionVoxelEdit = new QAction(MainWindow);
        actionVoxelEdit->setObjectName(QString::fromUtf8("actionVoxelEdit"));
        actionVoxelEdit->setCheckable(true);
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/resource/icons/voxel_edit.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionVoxelEdit->setIcon(icon5);
        actionROIEdit = new QAction(MainWindow);
        actionROIEdit->setObjectName(QString::fromUtf8("actionROIEdit"));
        actionROIEdit->setCheckable(true);
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/resource/icons/roi_edit.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionROIEdit->setIcon(icon6);
        actionPointSetEdit = new QAction(MainWindow);
        actionPointSetEdit->setObjectName(QString::fromUtf8("actionPointSetEdit"));
        actionPointSetEdit->setCheckable(true);
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/resource/icons/waypoints_edit.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionPointSetEdit->setIcon(icon7);
        actionLoadDTIVolumes = new QAction(MainWindow);
        actionLoadDTIVolumes->setObjectName(QString::fromUtf8("actionLoadDTIVolumes"));
        actionLoadSurface = new QAction(MainWindow);
        actionLoadSurface->setObjectName(QString::fromUtf8("actionLoadSurface"));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8(":/resource/icons/surface_load.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionLoadSurface->setIcon(icon8);
        actionSaveSurface = new QAction(MainWindow);
        actionSaveSurface->setObjectName(QString::fromUtf8("actionSaveSurface"));
        actionSaveSurfaceAs = new QAction(MainWindow);
        actionSaveSurfaceAs->setObjectName(QString::fromUtf8("actionSaveSurfaceAs"));
        actionNewROI = new QAction(MainWindow);
        actionNewROI->setObjectName(QString::fromUtf8("actionNewROI"));
        QIcon icon9;
        icon9.addFile(QString::fromUtf8(":/resource/icons/roi_new.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionNewROI->setIcon(icon9);
        actionLoadROI = new QAction(MainWindow);
        actionLoadROI->setObjectName(QString::fromUtf8("actionLoadROI"));
        QIcon icon10;
        icon10.addFile(QString::fromUtf8(":/resource/icons/roi_load.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionLoadROI->setIcon(icon10);
        actionSaveROI = new QAction(MainWindow);
        actionSaveROI->setObjectName(QString::fromUtf8("actionSaveROI"));
        QIcon icon11;
        icon11.addFile(QString::fromUtf8(":/resource/icons/roi_save.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSaveROI->setIcon(icon11);
        actionSaveROIAs = new QAction(MainWindow);
        actionSaveROIAs->setObjectName(QString::fromUtf8("actionSaveROIAs"));
        actionNewPointSet = new QAction(MainWindow);
        actionNewPointSet->setObjectName(QString::fromUtf8("actionNewPointSet"));
        QIcon icon12;
        icon12.addFile(QString::fromUtf8(":/resource/icons/waypoints_new.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionNewPointSet->setIcon(icon12);
        actionLoadPointSet = new QAction(MainWindow);
        actionLoadPointSet->setObjectName(QString::fromUtf8("actionLoadPointSet"));
        QIcon icon13;
        icon13.addFile(QString::fromUtf8(":/resource/icons/waypoints_load.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionLoadPointSet->setIcon(icon13);
        actionSavePointSet = new QAction(MainWindow);
        actionSavePointSet->setObjectName(QString::fromUtf8("actionSavePointSet"));
        QIcon icon14;
        icon14.addFile(QString::fromUtf8(":/resource/icons/waypoints_save.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSavePointSet->setIcon(icon14);
        actionSavePointSetAs = new QAction(MainWindow);
        actionSavePointSetAs->setObjectName(QString::fromUtf8("actionSavePointSetAs"));
        actionSaveScreenshot = new QAction(MainWindow);
        actionSaveScreenshot->setObjectName(QString::fromUtf8("actionSaveScreenshot"));
        QIcon icon15;
        icon15.addFile(QString::fromUtf8(":/resource/icons/file_screenshot.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSaveScreenshot->setIcon(icon15);
        QFont font;
        actionSaveScreenshot->setFont(font);
        actionSaveMovieFrames = new QAction(MainWindow);
        actionSaveMovieFrames->setObjectName(QString::fromUtf8("actionSaveMovieFrames"));
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName(QString::fromUtf8("actionExit"));
        actionCopy = new QAction(MainWindow);
        actionCopy->setObjectName(QString::fromUtf8("actionCopy"));
        QIcon icon16;
        icon16.addFile(QString::fromUtf8(":/resource/icons/edit_copy.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCopy->setIcon(icon16);
        actionCopyStructure = new QAction(MainWindow);
        actionCopyStructure->setObjectName(QString::fromUtf8("actionCopyStructure"));
        actionPaste = new QAction(MainWindow);
        actionPaste->setObjectName(QString::fromUtf8("actionPaste"));
        QIcon icon17;
        icon17.addFile(QString::fromUtf8(":/resource/icons/edit_paste.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionPaste->setIcon(icon17);
        actionUndo = new QAction(MainWindow);
        actionUndo->setObjectName(QString::fromUtf8("actionUndo"));
        QIcon icon18;
        icon18.addFile(QString::fromUtf8(":/resource/icons/edit_undo.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionUndo->setIcon(icon18);
        actionRedo = new QAction(MainWindow);
        actionRedo->setObjectName(QString::fromUtf8("actionRedo"));
        QIcon icon19;
        icon19.addFile(QString::fromUtf8(":/resource/icons/edit_redo.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRedo->setIcon(icon19);
        actionRenameLayer = new QAction(MainWindow);
        actionRenameLayer->setObjectName(QString::fromUtf8("actionRenameLayer"));
        actionPreferences = new QAction(MainWindow);
        actionPreferences->setObjectName(QString::fromUtf8("actionPreferences"));
        actionLayout1x1 = new QAction(MainWindow);
        actionLayout1x1->setObjectName(QString::fromUtf8("actionLayout1x1"));
        actionLayout1x1->setCheckable(true);
        QIcon icon20;
        icon20.addFile(QString::fromUtf8(":/resource/icons/layout_1x1.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionLayout1x1->setIcon(icon20);
        actionLayout2x2 = new QAction(MainWindow);
        actionLayout2x2->setObjectName(QString::fromUtf8("actionLayout2x2"));
        actionLayout2x2->setCheckable(true);
        actionLayout2x2->setChecked(true);
        QIcon icon21;
        icon21.addFile(QString::fromUtf8(":/resource/icons/layout_2x2.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionLayout2x2->setIcon(icon21);
        actionLayout1n3 = new QAction(MainWindow);
        actionLayout1n3->setObjectName(QString::fromUtf8("actionLayout1n3"));
        actionLayout1n3->setCheckable(true);
        QIcon icon22;
        icon22.addFile(QString::fromUtf8(":/resource/icons/layout_1n3.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionLayout1n3->setIcon(icon22);
        actionLayout1n3h = new QAction(MainWindow);
        actionLayout1n3h->setObjectName(QString::fromUtf8("actionLayout1n3h"));
        actionLayout1n3h->setCheckable(true);
        QIcon icon23;
        icon23.addFile(QString::fromUtf8(":/resource/icons/layout_1n3_h.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionLayout1n3h->setIcon(icon23);
        actionViewSagittal = new QAction(MainWindow);
        actionViewSagittal->setObjectName(QString::fromUtf8("actionViewSagittal"));
        actionViewSagittal->setCheckable(true);
        actionViewSagittal->setChecked(true);
        QIcon icon24;
        icon24.addFile(QString::fromUtf8(":/resource/icons/view_sagittal.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionViewSagittal->setIcon(icon24);
        actionViewCoronal = new QAction(MainWindow);
        actionViewCoronal->setObjectName(QString::fromUtf8("actionViewCoronal"));
        actionViewCoronal->setCheckable(true);
        QIcon icon25;
        icon25.addFile(QString::fromUtf8(":/resource/icons/view_coronal.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionViewCoronal->setIcon(icon25);
        actionViewAxial = new QAction(MainWindow);
        actionViewAxial->setObjectName(QString::fromUtf8("actionViewAxial"));
        actionViewAxial->setCheckable(true);
        QIcon icon26;
        icon26.addFile(QString::fromUtf8(":/resource/icons/view_axial.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionViewAxial->setIcon(icon26);
        actionView3D = new QAction(MainWindow);
        actionView3D->setObjectName(QString::fromUtf8("actionView3D"));
        actionView3D->setCheckable(true);
        QIcon icon27;
        icon27.addFile(QString::fromUtf8(":/resource/icons/view_3d.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionView3D->setIcon(icon27);
        actionShowControlPanel = new QAction(MainWindow);
        actionShowControlPanel->setObjectName(QString::fromUtf8("actionShowControlPanel"));
        actionShowControlPanel->setCheckable(true);
        actionShowControlPanel->setChecked(true);
        QIcon icon28;
        icon28.addFile(QString::fromUtf8(":/resource/icons/view_control_panel.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionShowControlPanel->setIcon(icon28);
        actionResetView = new QAction(MainWindow);
        actionResetView->setObjectName(QString::fromUtf8("actionResetView"));
        actionResetViewNearestAxis = new QAction(MainWindow);
        actionResetViewNearestAxis->setObjectName(QString::fromUtf8("actionResetViewNearestAxis"));
        actionShowCoordinateAnnotation = new QAction(MainWindow);
        actionShowCoordinateAnnotation->setObjectName(QString::fromUtf8("actionShowCoordinateAnnotation"));
        actionShowCoordinateAnnotation->setCheckable(true);
        actionShowCoordinateAnnotation->setChecked(true);
        QIcon icon29;
        icon29.addFile(QString::fromUtf8(":/resource/icons/view_coordinate.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionShowCoordinateAnnotation->setIcon(icon29);
        actionShowColorScale = new QAction(MainWindow);
        actionShowColorScale->setObjectName(QString::fromUtf8("actionShowColorScale"));
        actionShowColorScale->setCheckable(true);
        QIcon icon30;
        icon30.addFile(QString::fromUtf8(":/resource/icons/view_scalar_bar.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionShowColorScale->setIcon(icon30);
        actionShowSliceFrames = new QAction(MainWindow);
        actionShowSliceFrames->setObjectName(QString::fromUtf8("actionShowSliceFrames"));
        actionShowSliceFrames->setCheckable(true);
        actionToggleCursorVisibility = new QAction(MainWindow);
        actionToggleCursorVisibility->setObjectName(QString::fromUtf8("actionToggleCursorVisibility"));
        actionToggleCursorVisibility->setCheckable(true);
        actionToggleVoxelCoordinateDisplay = new QAction(MainWindow);
        actionToggleVoxelCoordinateDisplay->setObjectName(QString::fromUtf8("actionToggleVoxelCoordinateDisplay"));
        actionShowAllLayers = new QAction(MainWindow);
        actionShowAllLayers->setObjectName(QString::fromUtf8("actionShowAllLayers"));
        actionHideAllLayers = new QAction(MainWindow);
        actionHideAllLayers->setObjectName(QString::fromUtf8("actionHideAllLayers"));
        actionCycleLayer = new QAction(MainWindow);
        actionCycleLayer->setObjectName(QString::fromUtf8("actionCycleLayer"));
        actionReverseCycleLayer = new QAction(MainWindow);
        actionReverseCycleLayer->setObjectName(QString::fromUtf8("actionReverseCycleLayer"));
        actionToggleVolumeVisibility = new QAction(MainWindow);
        actionToggleVolumeVisibility->setObjectName(QString::fromUtf8("actionToggleVolumeVisibility"));
        actionToggleSurfaceVisibility = new QAction(MainWindow);
        actionToggleSurfaceVisibility->setObjectName(QString::fromUtf8("actionToggleSurfaceVisibility"));
        actionToggleROIVisibility = new QAction(MainWindow);
        actionToggleROIVisibility->setObjectName(QString::fromUtf8("actionToggleROIVisibility"));
        actionTogglePointSetVisibility = new QAction(MainWindow);
        actionTogglePointSetVisibility->setObjectName(QString::fromUtf8("actionTogglePointSetVisibility"));
        actionTransformVolume = new QAction(MainWindow);
        actionTransformVolume->setObjectName(QString::fromUtf8("actionTransformVolume"));
        actionCropVolume = new QAction(MainWindow);
        actionCropVolume->setObjectName(QString::fromUtf8("actionCropVolume"));
        actionCreateOptimalCombinedVolume = new QAction(MainWindow);
        actionCreateOptimalCombinedVolume->setObjectName(QString::fromUtf8("actionCreateOptimalCombinedVolume"));
        actionRepositionSurface = new QAction(MainWindow);
        actionRepositionSurface->setObjectName(QString::fromUtf8("actionRepositionSurface"));
        actionSavePoint = new QAction(MainWindow);
        actionSavePoint->setObjectName(QString::fromUtf8("actionSavePoint"));
        QIcon icon31;
        icon31.addFile(QString::fromUtf8(":/resource/icons/tool_save_point.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSavePoint->setIcon(icon31);
        actionGoToPoint = new QAction(MainWindow);
        actionGoToPoint->setObjectName(QString::fromUtf8("actionGoToPoint"));
        QIcon icon32;
        icon32.addFile(QString::fromUtf8(":/resource/icons/tool_goto_point.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionGoToPoint->setIcon(icon32);
        actionShowLabelStats = new QAction(MainWindow);
        actionShowLabelStats->setObjectName(QString::fromUtf8("actionShowLabelStats"));
        actionQuickReference = new QAction(MainWindow);
        actionQuickReference->setObjectName(QString::fromUtf8("actionQuickReference"));
        actionAbout = new QAction(MainWindow);
        actionAbout->setObjectName(QString::fromUtf8("actionAbout"));
        actionVolumeFilterMean = new QAction(MainWindow);
        actionVolumeFilterMean->setObjectName(QString::fromUtf8("actionVolumeFilterMean"));
        actionVolumeFilterMedian = new QAction(MainWindow);
        actionVolumeFilterMedian->setObjectName(QString::fromUtf8("actionVolumeFilterMedian"));
        actionVolumeFilterConvolve = new QAction(MainWindow);
        actionVolumeFilterConvolve->setObjectName(QString::fromUtf8("actionVolumeFilterConvolve"));
        actionVolumeFilterGradient = new QAction(MainWindow);
        actionVolumeFilterGradient->setObjectName(QString::fromUtf8("actionVolumeFilterGradient"));
        actionCloseVolume = new QAction(MainWindow);
        actionCloseVolume->setObjectName(QString::fromUtf8("actionCloseVolume"));
        QIcon icon33;
        icon33.addFile(QString::fromUtf8(":/resource/icons/volume_delete.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCloseVolume->setIcon(icon33);
        actionCloseSurface = new QAction(MainWindow);
        actionCloseSurface->setObjectName(QString::fromUtf8("actionCloseSurface"));
        QIcon icon34;
        icon34.addFile(QString::fromUtf8(":/resource/icons/surface_delete.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCloseSurface->setIcon(icon34);
        actionCloseROI = new QAction(MainWindow);
        actionCloseROI->setObjectName(QString::fromUtf8("actionCloseROI"));
        QIcon icon35;
        icon35.addFile(QString::fromUtf8(":/resource/icons/roi_delete.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCloseROI->setIcon(icon35);
        actionClosePointSet = new QAction(MainWindow);
        actionClosePointSet->setObjectName(QString::fromUtf8("actionClosePointSet"));
        QIcon icon36;
        icon36.addFile(QString::fromUtf8(":/resource/icons/waypoints_delete.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionClosePointSet->setIcon(icon36);
        actionVolumes = new QAction(MainWindow);
        actionVolumes->setObjectName(QString::fromUtf8("actionVolumes"));
        actionVolumes->setEnabled(false);
        QFont font1;
        font1.setBold(true);
        font1.setWeight(75);
        actionVolumes->setFont(font1);
        actionSurfaces = new QAction(MainWindow);
        actionSurfaces->setObjectName(QString::fromUtf8("actionSurfaces"));
        actionSurfaces->setEnabled(false);
        actionSurfaces->setFont(font1);
        actionVolumeFilterSobel = new QAction(MainWindow);
        actionVolumeFilterSobel->setObjectName(QString::fromUtf8("actionVolumeFilterSobel"));
        actionRunCommand = new QAction(MainWindow);
        actionRunCommand->setObjectName(QString::fromUtf8("actionRunCommand"));
        actionLoadCommand = new QAction(MainWindow);
        actionLoadCommand->setObjectName(QString::fromUtf8("actionLoadCommand"));
        actionShowCommandConsole = new QAction(MainWindow);
        actionShowCommandConsole->setObjectName(QString::fromUtf8("actionShowCommandConsole"));
        actionShowCommandConsole->setCheckable(true);
        QIcon icon37;
        icon37.addFile(QString::fromUtf8(":/resource/icons/view_command_console.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionShowCommandConsole->setIcon(icon37);
        actionLoadTrack = new QAction(MainWindow);
        actionLoadTrack->setObjectName(QString::fromUtf8("actionLoadTrack"));
        QIcon icon38;
        icon38.addFile(QString::fromUtf8(":/resource/icons/track_load.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionLoadTrack->setIcon(icon38);
        actionCloseTrack = new QAction(MainWindow);
        actionCloseTrack->setObjectName(QString::fromUtf8("actionCloseTrack"));
        QIcon icon39;
        icon39.addFile(QString::fromUtf8(":/resource/icons/track_delete.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCloseTrack->setIcon(icon39);
        actionShowSlices = new QAction(MainWindow);
        actionShowSlices->setObjectName(QString::fromUtf8("actionShowSlices"));
        actionShowSlices->setCheckable(true);
        actionLoadTrackVolume = new QAction(MainWindow);
        actionLoadTrackVolume->setObjectName(QString::fromUtf8("actionLoadTrackVolume"));
        actionIncreaseOpacity = new QAction(MainWindow);
        actionIncreaseOpacity->setObjectName(QString::fromUtf8("actionIncreaseOpacity"));
        actionDecreaseOpacity = new QAction(MainWindow);
        actionDecreaseOpacity->setObjectName(QString::fromUtf8("actionDecreaseOpacity"));
        actionIntensityProject = new QAction(MainWindow);
        actionIntensityProject->setObjectName(QString::fromUtf8("actionIntensityProject"));
        actionTimeCourse = new QAction(MainWindow);
        actionTimeCourse->setObjectName(QString::fromUtf8("actionTimeCourse"));
        actionTimeCourse->setCheckable(true);
        actionTimeCourse->setChecked(true);
        QIcon icon40;
        icon40.addFile(QString::fromUtf8(":/resource/icons/view_time_course.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionTimeCourse->setIcon(icon40);
        actionPlot = new QAction(MainWindow);
        actionPlot->setObjectName(QString::fromUtf8("actionPlot"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        horizontalLayout = new QHBoxLayout(centralWidget);
        horizontalLayout->setSpacing(6);
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        splitterMain = new QSplitter(centralWidget);
        splitterMain->setObjectName(QString::fromUtf8("splitterMain"));
        splitterMain->setFrameShape(QFrame::NoFrame);
        splitterMain->setOrientation(Qt::Horizontal);
        splitterMain->setHandleWidth(5);
        splitterMain->setChildrenCollapsible(false);
        tabWidgetControlPanel = new QTabWidget(splitterMain);
        tabWidgetControlPanel->setObjectName(QString::fromUtf8("tabWidgetControlPanel"));
        tabWidgetControlPanel->setMinimumSize(QSize(0, 0));
        tabWidgetControlPanel->setTabShape(QTabWidget::Rounded);
        tabWidgetControlPanel->setElideMode(Qt::ElideNone);
        tabWidgetControlPanel->setUsesScrollButtons(true);
        tabWidgetControlPanel->setDocumentMode(false);
        tabWidgetControlPanel->setMovable(true);
        tabVolume = new PanelVolume();
        tabVolume->setObjectName(QString::fromUtf8("tabVolume"));
        tabWidgetControlPanel->addTab(tabVolume, QString());
        tabSurface = new PanelSurface();
        tabSurface->setObjectName(QString::fromUtf8("tabSurface"));
        tabWidgetControlPanel->addTab(tabSurface, QString());
        tabROI = new PanelROI();
        tabROI->setObjectName(QString::fromUtf8("tabROI"));
        tabWidgetControlPanel->addTab(tabROI, QString());
        tabPointSet = new PanelPointSet();
        tabPointSet->setObjectName(QString::fromUtf8("tabPointSet"));
        tabWidgetControlPanel->addTab(tabPointSet, QString());
        tabTrack = new PanelTrack();
        tabTrack->setObjectName(QString::fromUtf8("tabTrack"));
        tabWidgetControlPanel->addTab(tabTrack, QString());
        splitterMain->addWidget(tabWidgetControlPanel);
        widget = new QWidget(splitterMain);
        widget->setObjectName(QString::fromUtf8("widget"));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(1);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(widget->sizePolicy().hasHeightForWidth());
        widget->setSizePolicy(sizePolicy);
        horizontalLayout_2 = new QHBoxLayout(widget);
        horizontalLayout_2->setSpacing(0);
        horizontalLayout_2->setContentsMargins(0, 0, 0, 0);
        horizontalLayout_2->setObjectName(QString::fromUtf8("horizontalLayout_2"));
        splitterInfoPanel = new QSplitter(widget);
        splitterInfoPanel->setObjectName(QString::fromUtf8("splitterInfoPanel"));
        splitterInfoPanel->setOrientation(Qt::Vertical);
        splitterInfoPanel->setHandleWidth(5);
        splitterInfoPanel->setChildrenCollapsible(false);
        widgetViewportHolder = new QWidget(splitterInfoPanel);
        widgetViewportHolder->setObjectName(QString::fromUtf8("widgetViewportHolder"));
        QSizePolicy sizePolicy1(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(1);
        sizePolicy1.setHeightForWidth(widgetViewportHolder->sizePolicy().hasHeightForWidth());
        widgetViewportHolder->setSizePolicy(sizePolicy1);
        widgetViewportHolder->setMinimumSize(QSize(100, 100));
        widgetViewportHolder->setAutoFillBackground(true);
        gridLayoutViewport = new QGridLayout(widgetViewportHolder);
        gridLayoutViewport->setSpacing(1);
        gridLayoutViewport->setContentsMargins(0, 0, 0, 0);
        gridLayoutViewport->setObjectName(QString::fromUtf8("gridLayoutViewport"));
        viewAxial = new RenderView2D(widgetViewportHolder);
        viewAxial->setObjectName(QString::fromUtf8("viewAxial"));
        viewAxial->setMouseTracking(true);

        gridLayoutViewport->addWidget(viewAxial, 0, 0, 1, 1);

        viewSagittal = new RenderView2D(widgetViewportHolder);
        viewSagittal->setObjectName(QString::fromUtf8("viewSagittal"));
        viewSagittal->setMouseTracking(true);

        gridLayoutViewport->addWidget(viewSagittal, 0, 1, 1, 1);

        viewCoronal = new RenderView2D(widgetViewportHolder);
        viewCoronal->setObjectName(QString::fromUtf8("viewCoronal"));
        viewCoronal->setMouseTracking(true);

        gridLayoutViewport->addWidget(viewCoronal, 1, 0, 1, 1);

        view3D = new RenderView3D(widgetViewportHolder);
        view3D->setObjectName(QString::fromUtf8("view3D"));
        view3D->setMouseTracking(true);

        gridLayoutViewport->addWidget(view3D, 1, 1, 1, 1);

        splitterInfoPanel->addWidget(widgetViewportHolder);
        widget_3 = new QWidget(splitterInfoPanel);
        widget_3->setObjectName(QString::fromUtf8("widget_3"));
        horizontalLayout_3 = new QHBoxLayout(widget_3);
        horizontalLayout_3->setSpacing(2);
        horizontalLayout_3->setContentsMargins(0, 0, 0, 0);
        horizontalLayout_3->setObjectName(QString::fromUtf8("horizontalLayout_3"));
        treeWidgetCursorInfo = new InfoTreeWidget(widget_3);
        QTreeWidgetItem *__qtreewidgetitem = new QTreeWidgetItem();
        __qtreewidgetitem->setText(0, QString::fromUtf8("Cursor"));
        treeWidgetCursorInfo->setHeaderItem(__qtreewidgetitem);
        treeWidgetCursorInfo->setObjectName(QString::fromUtf8("treeWidgetCursorInfo"));
        treeWidgetCursorInfo->setRootIsDecorated(false);
        treeWidgetCursorInfo->setUniformRowHeights(true);
        treeWidgetCursorInfo->setColumnCount(2);
        treeWidgetCursorInfo->header()->setCascadingSectionResizes(false);

        horizontalLayout_3->addWidget(treeWidgetCursorInfo);

        treeWidgetMouseInfo = new InfoTreeWidget(widget_3);
        treeWidgetMouseInfo->setObjectName(QString::fromUtf8("treeWidgetMouseInfo"));
        treeWidgetMouseInfo->setRootIsDecorated(false);
        treeWidgetMouseInfo->setUniformRowHeights(true);

        horizontalLayout_3->addWidget(treeWidgetMouseInfo);

        splitterInfoPanel->addWidget(widget_3);

        horizontalLayout_2->addWidget(splitterInfoPanel);

        splitterMain->addWidget(widget);

        horizontalLayout->addWidget(splitterMain);

        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1213, 25));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        menuRecentFiles = new QMenu(menuFile);
        menuRecentFiles->setObjectName(QString::fromUtf8("menuRecentFiles"));
        menuEdit = new QMenu(menuBar);
        menuEdit->setObjectName(QString::fromUtf8("menuEdit"));
        menuView = new QMenu(menuBar);
        menuView->setObjectName(QString::fromUtf8("menuView"));
        menuViewport_Layout = new QMenu(menuView);
        menuViewport_Layout->setObjectName(QString::fromUtf8("menuViewport_Layout"));
        menuLayer = new QMenu(menuBar);
        menuLayer->setObjectName(QString::fromUtf8("menuLayer"));
        menuAction = new QMenu(menuBar);
        menuAction->setObjectName(QString::fromUtf8("menuAction"));
        menuTools = new QMenu(menuBar);
        menuTools->setObjectName(QString::fromUtf8("menuTools"));
        menuVolume_Fiilter = new QMenu(menuTools);
        menuVolume_Fiilter->setObjectName(QString::fromUtf8("menuVolume_Fiilter"));
        menuHelp = new QMenu(menuBar);
        menuHelp->setObjectName(QString::fromUtf8("menuHelp"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        mainToolBar->setMovable(false);
        mainToolBar->setAllowedAreas(Qt::TopToolBarArea);
        mainToolBar->setToolButtonStyle(Qt::ToolButtonIconOnly);
        mainToolBar->setFloatable(false);
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuEdit->menuAction());
        menuBar->addAction(menuView->menuAction());
        menuBar->addAction(menuLayer->menuAction());
        menuBar->addAction(menuAction->menuAction());
        menuBar->addAction(menuTools->menuAction());
        menuBar->addAction(menuHelp->menuAction());
        menuFile->addAction(actionNewVolume);
        menuFile->addAction(actionLoadVolume);
        menuFile->addAction(actionSaveVolume);
        menuFile->addAction(actionCloseVolume);
        menuFile->addAction(actionSaveVolumeAs);
        menuFile->addSeparator();
        menuFile->addAction(actionLoadDTIVolumes);
        menuFile->addAction(actionLoadTrackVolume);
        menuFile->addSeparator();
        menuFile->addAction(actionLoadSurface);
        menuFile->addAction(actionSaveSurface);
        menuFile->addAction(actionSaveSurfaceAs);
        menuFile->addSeparator();
        menuFile->addAction(actionNewROI);
        menuFile->addAction(actionLoadROI);
        menuFile->addAction(actionSaveROI);
        menuFile->addAction(actionSaveROIAs);
        menuFile->addSeparator();
        menuFile->addAction(actionNewPointSet);
        menuFile->addAction(actionLoadPointSet);
        menuFile->addAction(actionSavePointSet);
        menuFile->addAction(actionSavePointSetAs);
        menuFile->addSeparator();
        menuFile->addAction(actionLoadTrack);
        menuFile->addSeparator();
        menuFile->addAction(actionSaveScreenshot);
        menuFile->addAction(actionSaveMovieFrames);
        menuFile->addSeparator();
        menuFile->addAction(actionRunCommand);
        menuFile->addAction(actionLoadCommand);
        menuFile->addSeparator();
        menuFile->addAction(menuRecentFiles->menuAction());
        menuFile->addSeparator();
        menuFile->addAction(actionExit);
        menuRecentFiles->addAction(actionVolumes);
        menuRecentFiles->addAction(actionSurfaces);
        menuEdit->addAction(actionCopy);
        menuEdit->addAction(actionCopyStructure);
        menuEdit->addAction(actionPaste);
        menuEdit->addSeparator();
        menuEdit->addAction(actionUndo);
        menuEdit->addAction(actionRedo);
        menuEdit->addSeparator();
        menuEdit->addAction(actionPreferences);
        menuView->addAction(menuViewport_Layout->menuAction());
        menuView->addAction(actionShowControlPanel);
        menuView->addAction(actionShowCommandConsole);
        menuView->addAction(actionResetView);
        menuView->addAction(actionResetViewNearestAxis);
        menuView->addSeparator();
        menuView->addAction(actionShowCoordinateAnnotation);
        menuView->addAction(actionShowColorScale);
        menuView->addAction(actionTimeCourse);
        menuView->addAction(actionToggleCursorVisibility);
        menuView->addAction(actionShowSlices);
        menuView->addAction(actionShowSliceFrames);
        menuViewport_Layout->addAction(actionLayout1x1);
        menuViewport_Layout->addAction(actionLayout2x2);
        menuViewport_Layout->addAction(actionLayout1n3);
        menuViewport_Layout->addAction(actionLayout1n3h);
        menuViewport_Layout->addSeparator();
        menuViewport_Layout->addAction(actionViewSagittal);
        menuViewport_Layout->addAction(actionViewCoronal);
        menuViewport_Layout->addAction(actionViewAxial);
        menuViewport_Layout->addAction(actionView3D);
        menuLayer->addAction(actionShowAllLayers);
        menuLayer->addAction(actionHideAllLayers);
        menuLayer->addSeparator();
        menuLayer->addAction(actionCycleLayer);
        menuLayer->addAction(actionReverseCycleLayer);
        menuLayer->addSeparator();
        menuLayer->addAction(actionToggleVolumeVisibility);
        menuLayer->addAction(actionToggleSurfaceVisibility);
        menuLayer->addAction(actionToggleROIVisibility);
        menuLayer->addAction(actionTogglePointSetVisibility);
        menuAction->addAction(actionNavigate);
        menuAction->addAction(actionMeasure);
        menuAction->addAction(actionVoxelEdit);
        menuAction->addAction(actionROIEdit);
        menuAction->addAction(actionPointSetEdit);
        menuTools->addAction(menuVolume_Fiilter->menuAction());
        menuTools->addAction(actionTransformVolume);
        menuTools->addAction(actionCropVolume);
        menuTools->addAction(actionCreateOptimalCombinedVolume);
        menuTools->addSeparator();
        menuTools->addAction(actionRepositionSurface);
        menuTools->addSeparator();
        menuTools->addAction(actionSavePoint);
        menuTools->addAction(actionGoToPoint);
        menuTools->addSeparator();
        menuTools->addAction(actionShowLabelStats);
        menuTools->addSeparator();
        menuTools->addAction(actionPlot);
        menuVolume_Fiilter->addAction(actionVolumeFilterMean);
        menuVolume_Fiilter->addAction(actionVolumeFilterMedian);
        menuVolume_Fiilter->addAction(actionVolumeFilterConvolve);
        menuVolume_Fiilter->addAction(actionVolumeFilterGradient);
        menuVolume_Fiilter->addAction(actionVolumeFilterSobel);
        menuHelp->addAction(actionQuickReference);
        menuHelp->addAction(actionAbout);
        mainToolBar->addAction(actionNavigate);
        mainToolBar->addAction(actionMeasure);
        mainToolBar->addAction(actionVoxelEdit);
        mainToolBar->addAction(actionROIEdit);
        mainToolBar->addAction(actionPointSetEdit);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionUndo);
        mainToolBar->addAction(actionRedo);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionShowControlPanel);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionLayout1x1);
        mainToolBar->addAction(actionLayout2x2);
        mainToolBar->addAction(actionLayout1n3);
        mainToolBar->addAction(actionLayout1n3h);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionViewSagittal);
        mainToolBar->addAction(actionViewCoronal);
        mainToolBar->addAction(actionViewAxial);
        mainToolBar->addAction(actionView3D);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionShowCoordinateAnnotation);
        mainToolBar->addAction(actionShowColorScale);
        mainToolBar->addAction(actionTimeCourse);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionSaveScreenshot);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionSavePoint);
        mainToolBar->addAction(actionGoToPoint);

        retranslateUi(MainWindow);
        QObject::connect(actionShowControlPanel, SIGNAL(toggled(bool)), tabWidgetControlPanel, SLOT(setVisible(bool)));
        QObject::connect(actionExit, SIGNAL(triggered()), MainWindow, SLOT(close()));
        QObject::connect(actionLoadVolume, SIGNAL(triggered()), MainWindow, SLOT(OnLoadVolume()));
        QObject::connect(actionCloseVolume, SIGNAL(triggered()), MainWindow, SLOT(OnCloseVolume()));
        QObject::connect(actionCycleLayer, SIGNAL(triggered()), MainWindow, SLOT(OnCycleLayer()));
        QObject::connect(actionReverseCycleLayer, SIGNAL(triggered()), MainWindow, SLOT(OnReverseCycleLayer()));
        QObject::connect(actionLoadSurface, SIGNAL(triggered()), MainWindow, SLOT(OnLoadSurface()));
        QObject::connect(actionCloseSurface, SIGNAL(triggered()), MainWindow, SLOT(OnCloseSurface()));
        QObject::connect(actionNavigate, SIGNAL(triggered()), MainWindow, SLOT(OnSetModeNavigate()));
        QObject::connect(actionMeasure, SIGNAL(triggered()), MainWindow, SLOT(OnSetModeMeasure()));
        QObject::connect(actionPointSetEdit, SIGNAL(triggered()), MainWindow, SLOT(OnSetModePointSetEdit()));
        QObject::connect(actionVoxelEdit, SIGNAL(triggered()), MainWindow, SLOT(OnSetModeVoxelEdit()));
        QObject::connect(actionROIEdit, SIGNAL(triggered()), MainWindow, SLOT(OnSetModeROIEdit()));
        QObject::connect(actionUndo, SIGNAL(triggered()), MainWindow, SLOT(OnEditUndo()));
        QObject::connect(actionRedo, SIGNAL(triggered()), MainWindow, SLOT(OnEditRedo()));
        QObject::connect(actionSaveVolume, SIGNAL(triggered()), MainWindow, SLOT(OnSaveVolume()));
        QObject::connect(actionNewVolume, SIGNAL(triggered()), MainWindow, SLOT(OnNewVolume()));
        QObject::connect(actionSaveROI, SIGNAL(triggered()), MainWindow, SLOT(OnSaveROI()));
        QObject::connect(actionLoadROI, SIGNAL(triggered()), MainWindow, SLOT(OnLoadROI()));
        QObject::connect(actionNewROI, SIGNAL(triggered()), MainWindow, SLOT(OnNewROI()));
        QObject::connect(actionCloseROI, SIGNAL(triggered()), MainWindow, SLOT(OnCloseROI()));
        QObject::connect(actionNewPointSet, SIGNAL(triggered()), MainWindow, SLOT(OnNewPointSet()));
        QObject::connect(actionSavePointSet, SIGNAL(triggered()), MainWindow, SLOT(OnSavePointSet()));
        QObject::connect(actionClosePointSet, SIGNAL(triggered()), MainWindow, SLOT(OnClosePointSet()));
        QObject::connect(actionPreferences, SIGNAL(triggered()), MainWindow, SLOT(OnPreferences()));
        QObject::connect(actionLoadDTIVolumes, SIGNAL(triggered()), MainWindow, SLOT(OnLoadDTI()));
        QObject::connect(actionLoadPointSet, SIGNAL(triggered()), MainWindow, SLOT(OnLoadPointSet()));
        QObject::connect(actionTransformVolume, SIGNAL(triggered()), MainWindow, SLOT(OnTransformVolume()));
        QObject::connect(actionCropVolume, SIGNAL(triggered()), MainWindow, SLOT(OnCropVolume()));
        QObject::connect(actionSaveScreenshot, SIGNAL(triggered()), MainWindow, SLOT(OnSaveScreenshot()));
        QObject::connect(actionVolumeFilterMean, SIGNAL(triggered()), MainWindow, SLOT(OnVolumeFilterMean()));
        QObject::connect(actionVolumeFilterMedian, SIGNAL(triggered()), MainWindow, SLOT(OnVolumeFilterMedian()));
        QObject::connect(actionVolumeFilterConvolve, SIGNAL(triggered()), MainWindow, SLOT(OnVolumeFilterConvolve()));
        QObject::connect(actionVolumeFilterGradient, SIGNAL(triggered()), MainWindow, SLOT(OnVolumeFilterGradient()));
        QObject::connect(actionResetView, SIGNAL(triggered()), MainWindow, SLOT(OnResetView()));
        QObject::connect(actionResetViewNearestAxis, SIGNAL(triggered()), view3D, SLOT(SnapToNearestAxis()));
        QObject::connect(actionShowSliceFrames, SIGNAL(toggled(bool)), view3D, SLOT(SetShowSliceFrames(bool)));
        QObject::connect(actionGoToPoint, SIGNAL(triggered()), MainWindow, SLOT(OnGoToPoint()));
        QObject::connect(actionSavePoint, SIGNAL(triggered()), MainWindow, SLOT(OnSavePoint()));
        QObject::connect(actionShowAllLayers, SIGNAL(triggered()), MainWindow, SLOT(ShowAllLayers()));
        QObject::connect(actionHideAllLayers, SIGNAL(triggered()), MainWindow, SLOT(HideAllLayers()));
        QObject::connect(actionShowCoordinateAnnotation, SIGNAL(toggled(bool)), MainWindow, SLOT(OnShowAnnotation(bool)));
        QObject::connect(actionShowColorScale, SIGNAL(toggled(bool)), MainWindow, SLOT(OnShowColorBar(bool)));
        QObject::connect(actionCopy, SIGNAL(triggered()), MainWindow, SLOT(OnCopy()));
        QObject::connect(actionCopyStructure, SIGNAL(triggered()), MainWindow, SLOT(OnCopyStructure()));
        QObject::connect(actionPaste, SIGNAL(triggered()), MainWindow, SLOT(OnPaste()));
        QObject::connect(actionToggleVolumeVisibility, SIGNAL(triggered()), MainWindow, SLOT(OnToggleShowVolume()));
        QObject::connect(actionToggleSurfaceVisibility, SIGNAL(triggered()), MainWindow, SLOT(OnToggleShowSurface()));
        QObject::connect(actionToggleROIVisibility, SIGNAL(triggered()), MainWindow, SLOT(OnToggleShowROI()));
        QObject::connect(actionTogglePointSetVisibility, SIGNAL(triggered()), MainWindow, SLOT(OnToggleShowPointSet()));
        QObject::connect(actionAbout, SIGNAL(triggered()), MainWindow, SLOT(OnAbout()));
        QObject::connect(actionVolumeFilterSobel, SIGNAL(triggered()), MainWindow, SLOT(OnVolumeFilterSobel()));
        QObject::connect(actionSaveVolumeAs, SIGNAL(triggered()), MainWindow, SLOT(SaveVolumeAs()));
        QObject::connect(actionLoadCommand, SIGNAL(triggered()), MainWindow, SLOT(OnLoadCommand()));
        QObject::connect(actionLoadTrack, SIGNAL(triggered()), MainWindow, SLOT(OnLoadTrack()));
        QObject::connect(actionCloseTrack, SIGNAL(triggered()), MainWindow, SLOT(OnCloseTrack()));
        QObject::connect(actionSavePointSetAs, SIGNAL(triggered()), MainWindow, SLOT(OnSavePointSetAs()));
        QObject::connect(actionSaveMovieFrames, SIGNAL(triggered()), MainWindow, SLOT(OnWriteMovieFrames()));
        QObject::connect(actionLoadTrackVolume, SIGNAL(triggered()), MainWindow, SLOT(OnLoadTrackVolume()));
        QObject::connect(actionIncreaseOpacity, SIGNAL(triggered()), MainWindow, SLOT(OnIncreaseOpacity()));
        QObject::connect(actionDecreaseOpacity, SIGNAL(triggered()), MainWindow, SLOT(OnDecreaseOpacity()));
        QObject::connect(actionToggleCursorVisibility, SIGNAL(toggled(bool)), MainWindow, SLOT(OnToggleCursorVisibility(bool)));
        QObject::connect(actionRepositionSurface, SIGNAL(triggered()), MainWindow, SLOT(OnRepositionSurface()));
        QObject::connect(actionShowLabelStats, SIGNAL(triggered()), MainWindow, SLOT(OnShowLabelStats()));
        QObject::connect(actionSaveROIAs, SIGNAL(triggered()), MainWindow, SLOT(OnSaveROIAs()));
        QObject::connect(actionPlot, SIGNAL(triggered()), MainWindow, SLOT(OnPlot()));

        tabWidgetControlPanel->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "FreeView", 0, QApplication::UnicodeUTF8));
        actionNewVolume->setText(QApplication::translate("MainWindow", "New Volume...", 0, QApplication::UnicodeUTF8));
        actionLoadVolume->setText(QApplication::translate("MainWindow", "Load Volume...", 0, QApplication::UnicodeUTF8));
        actionLoadVolume->setShortcut(QApplication::translate("MainWindow", "Ctrl+O", 0, QApplication::UnicodeUTF8));
        actionSaveVolume->setText(QApplication::translate("MainWindow", "Save Volume", 0, QApplication::UnicodeUTF8));
        actionSaveVolume->setShortcut(QApplication::translate("MainWindow", "Ctrl+S", 0, QApplication::UnicodeUTF8));
        actionSaveVolumeAs->setText(QApplication::translate("MainWindow", "Save Volume As...", 0, QApplication::UnicodeUTF8));
        actionNavigate->setText(QApplication::translate("MainWindow", "Navigate", 0, QApplication::UnicodeUTF8));
        actionNavigate->setShortcut(QApplication::translate("MainWindow", "Alt+N", 0, QApplication::UnicodeUTF8));
        actionMeasure->setText(QApplication::translate("MainWindow", "Measure", 0, QApplication::UnicodeUTF8));
        actionVoxelEdit->setText(QApplication::translate("MainWindow", "Voxel Edit", 0, QApplication::UnicodeUTF8));
        actionVoxelEdit->setShortcut(QApplication::translate("MainWindow", "Alt+E", 0, QApplication::UnicodeUTF8));
        actionROIEdit->setText(QApplication::translate("MainWindow", "ROI Edit", 0, QApplication::UnicodeUTF8));
        actionPointSetEdit->setText(QApplication::translate("MainWindow", "Point Set Edit", 0, QApplication::UnicodeUTF8));
        actionLoadDTIVolumes->setText(QApplication::translate("MainWindow", "Load DTI Volume...", 0, QApplication::UnicodeUTF8));
        actionLoadSurface->setText(QApplication::translate("MainWindow", "Load Surface...", 0, QApplication::UnicodeUTF8));
        actionSaveSurface->setText(QApplication::translate("MainWindow", "Save Surface", 0, QApplication::UnicodeUTF8));
        actionSaveSurfaceAs->setText(QApplication::translate("MainWindow", "Save Surface As...", 0, QApplication::UnicodeUTF8));
        actionNewROI->setText(QApplication::translate("MainWindow", "New ROI...", 0, QApplication::UnicodeUTF8));
        actionLoadROI->setText(QApplication::translate("MainWindow", "Load ROI...", 0, QApplication::UnicodeUTF8));
        actionSaveROI->setText(QApplication::translate("MainWindow", "Save ROI...", 0, QApplication::UnicodeUTF8));
        actionSaveROIAs->setText(QApplication::translate("MainWindow", "Save ROI As...", 0, QApplication::UnicodeUTF8));
        actionNewPointSet->setText(QApplication::translate("MainWindow", "New Point Set...", 0, QApplication::UnicodeUTF8));
        actionLoadPointSet->setText(QApplication::translate("MainWindow", "Load Point Set...", 0, QApplication::UnicodeUTF8));
        actionSavePointSet->setText(QApplication::translate("MainWindow", "Save Point Set", 0, QApplication::UnicodeUTF8));
        actionSavePointSetAs->setText(QApplication::translate("MainWindow", "Save Point Set As...", 0, QApplication::UnicodeUTF8));
        actionSaveScreenshot->setText(QApplication::translate("MainWindow", "Save Screenshot As...", 0, QApplication::UnicodeUTF8));
        actionSaveMovieFrames->setText(QApplication::translate("MainWindow", "Save Movie Frames...", 0, QApplication::UnicodeUTF8));
        actionExit->setText(QApplication::translate("MainWindow", "Exit", 0, QApplication::UnicodeUTF8));
        actionExit->setShortcut(QApplication::translate("MainWindow", "Ctrl+Q", 0, QApplication::UnicodeUTF8));
        actionCopy->setText(QApplication::translate("MainWindow", "Copy", 0, QApplication::UnicodeUTF8));
        actionCopy->setShortcut(QApplication::translate("MainWindow", "Ctrl+C", 0, QApplication::UnicodeUTF8));
        actionCopyStructure->setText(QApplication::translate("MainWindow", "Copy Structure", 0, QApplication::UnicodeUTF8));
        actionCopyStructure->setShortcut(QApplication::translate("MainWindow", "Ctrl+Alt+C", 0, QApplication::UnicodeUTF8));
        actionPaste->setText(QApplication::translate("MainWindow", "Paste", 0, QApplication::UnicodeUTF8));
        actionPaste->setShortcut(QApplication::translate("MainWindow", "Ctrl+V", 0, QApplication::UnicodeUTF8));
        actionUndo->setText(QApplication::translate("MainWindow", "Undo", 0, QApplication::UnicodeUTF8));
        actionUndo->setShortcut(QApplication::translate("MainWindow", "Ctrl+Z", 0, QApplication::UnicodeUTF8));
        actionRedo->setText(QApplication::translate("MainWindow", "Redo", 0, QApplication::UnicodeUTF8));
        actionRedo->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+Z", 0, QApplication::UnicodeUTF8));
        actionRenameLayer->setText(QApplication::translate("MainWindow", "Rename Layer...", 0, QApplication::UnicodeUTF8));
        actionRenameLayer->setShortcut(QApplication::translate("MainWindow", "Ctrl+Alt+N", 0, QApplication::UnicodeUTF8));
        actionPreferences->setText(QApplication::translate("MainWindow", "Preferences...", 0, QApplication::UnicodeUTF8));
        actionLayout1x1->setText(QApplication::translate("MainWindow", "1 X 1", 0, QApplication::UnicodeUTF8));
        actionLayout2x2->setText(QApplication::translate("MainWindow", "2 X 2", 0, QApplication::UnicodeUTF8));
        actionLayout1n3->setText(QApplication::translate("MainWindow", "1 && 3", 0, QApplication::UnicodeUTF8));
        actionLayout1n3h->setText(QApplication::translate("MainWindow", "1 && 3 Horizontal", 0, QApplication::UnicodeUTF8));
        actionViewSagittal->setText(QApplication::translate("MainWindow", "Sagittal", 0, QApplication::UnicodeUTF8));
        actionViewSagittal->setShortcut(QApplication::translate("MainWindow", "Alt+X", 0, QApplication::UnicodeUTF8));
        actionViewCoronal->setText(QApplication::translate("MainWindow", "Coronal", 0, QApplication::UnicodeUTF8));
        actionViewCoronal->setShortcut(QApplication::translate("MainWindow", "Alt+Y", 0, QApplication::UnicodeUTF8));
        actionViewAxial->setText(QApplication::translate("MainWindow", "Axial", 0, QApplication::UnicodeUTF8));
        actionViewAxial->setShortcut(QApplication::translate("MainWindow", "Alt+Z", 0, QApplication::UnicodeUTF8));
        actionView3D->setText(QApplication::translate("MainWindow", "3D", 0, QApplication::UnicodeUTF8));
        actionView3D->setShortcut(QApplication::translate("MainWindow", "Alt+3", 0, QApplication::UnicodeUTF8));
        actionShowControlPanel->setText(QApplication::translate("MainWindow", "Show Control Panel", 0, QApplication::UnicodeUTF8));
        actionShowControlPanel->setShortcut(QApplication::translate("MainWindow", "Ctrl+P", 0, QApplication::UnicodeUTF8));
        actionResetView->setText(QApplication::translate("MainWindow", "Reset View", 0, QApplication::UnicodeUTF8));
        actionResetView->setShortcut(QApplication::translate("MainWindow", "Ctrl+R", 0, QApplication::UnicodeUTF8));
        actionResetViewNearestAxis->setText(QApplication::translate("MainWindow", "Reset View to Nearest Axis (3D View)", 0, QApplication::UnicodeUTF8));
        actionResetViewNearestAxis->setShortcut(QApplication::translate("MainWindow", "Alt+R", 0, QApplication::UnicodeUTF8));
        actionShowCoordinateAnnotation->setText(QApplication::translate("MainWindow", "Show Coordinate Annotation", 0, QApplication::UnicodeUTF8));
        actionShowColorScale->setText(QApplication::translate("MainWindow", "Show Color Scale", 0, QApplication::UnicodeUTF8));
        actionShowSliceFrames->setText(QApplication::translate("MainWindow", "Show Slice Frames (3D View)", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        actionShowSliceFrames->setToolTip(QApplication::translate("MainWindow", "Show Slice Frames (3D View)", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        actionToggleCursorVisibility->setText(QApplication::translate("MainWindow", "Show Cursor", 0, QApplication::UnicodeUTF8));
        actionToggleCursorVisibility->setShortcut(QApplication::translate("MainWindow", "Alt+U", 0, QApplication::UnicodeUTF8));
        actionToggleVoxelCoordinateDisplay->setText(QApplication::translate("MainWindow", "Toggle Voxel Coordinate Display", 0, QApplication::UnicodeUTF8));
        actionToggleVoxelCoordinateDisplay->setShortcut(QApplication::translate("MainWindow", "Alt+D", 0, QApplication::UnicodeUTF8));
        actionShowAllLayers->setText(QApplication::translate("MainWindow", "Show All Layers", 0, QApplication::UnicodeUTF8));
        actionShowAllLayers->setShortcut(QApplication::translate("MainWindow", "Ctrl+Alt+S", 0, QApplication::UnicodeUTF8));
        actionHideAllLayers->setText(QApplication::translate("MainWindow", "Hide All Layers", 0, QApplication::UnicodeUTF8));
        actionHideAllLayers->setShortcut(QApplication::translate("MainWindow", "Ctrl+Alt+H", 0, QApplication::UnicodeUTF8));
        actionCycleLayer->setText(QApplication::translate("MainWindow", "Cycle Through Layer List", 0, QApplication::UnicodeUTF8));
        actionCycleLayer->setShortcut(QApplication::translate("MainWindow", "Alt+C", 0, QApplication::UnicodeUTF8));
        actionReverseCycleLayer->setText(QApplication::translate("MainWindow", "Reverse Cycle Through Layer List", 0, QApplication::UnicodeUTF8));
        actionReverseCycleLayer->setShortcut(QApplication::translate("MainWindow", "Alt+Shift+C", 0, QApplication::UnicodeUTF8));
        actionToggleVolumeVisibility->setText(QApplication::translate("MainWindow", "Toggle Volume Visibility", 0, QApplication::UnicodeUTF8));
        actionToggleVolumeVisibility->setShortcut(QApplication::translate("MainWindow", "Alt+V", 0, QApplication::UnicodeUTF8));
        actionToggleSurfaceVisibility->setText(QApplication::translate("MainWindow", "Toggle Surface Visibility", 0, QApplication::UnicodeUTF8));
        actionToggleSurfaceVisibility->setShortcut(QApplication::translate("MainWindow", "Alt+F", 0, QApplication::UnicodeUTF8));
        actionToggleROIVisibility->setText(QApplication::translate("MainWindow", "Toggle ROI Visibility", 0, QApplication::UnicodeUTF8));
        actionToggleROIVisibility->setShortcut(QApplication::translate("MainWindow", "Alt+R", 0, QApplication::UnicodeUTF8));
        actionTogglePointSetVisibility->setText(QApplication::translate("MainWindow", "Toggle Point Set Visibility", 0, QApplication::UnicodeUTF8));
        actionTogglePointSetVisibility->setShortcut(QApplication::translate("MainWindow", "Alt+W", 0, QApplication::UnicodeUTF8));
        actionTransformVolume->setText(QApplication::translate("MainWindow", "Transform Volume...", 0, QApplication::UnicodeUTF8));
        actionCropVolume->setText(QApplication::translate("MainWindow", "Crop Volume...", 0, QApplication::UnicodeUTF8));
        actionCreateOptimalCombinedVolume->setText(QApplication::translate("MainWindow", "Create Optimal Combined Volume...", 0, QApplication::UnicodeUTF8));
        actionRepositionSurface->setText(QApplication::translate("MainWindow", "Reposition Surface...", 0, QApplication::UnicodeUTF8));
        actionSavePoint->setText(QApplication::translate("MainWindow", "Save Point", 0, QApplication::UnicodeUTF8));
        actionGoToPoint->setText(QApplication::translate("MainWindow", "Go To Saved Point", 0, QApplication::UnicodeUTF8));
        actionShowLabelStats->setText(QApplication::translate("MainWindow", "Show Label Stats...", 0, QApplication::UnicodeUTF8));
        actionQuickReference->setText(QApplication::translate("MainWindow", "Quick Reference...", 0, QApplication::UnicodeUTF8));
        actionAbout->setText(QApplication::translate("MainWindow", "About FreeView...", 0, QApplication::UnicodeUTF8));
        actionVolumeFilterMean->setText(QApplication::translate("MainWindow", "Mean...", 0, QApplication::UnicodeUTF8));
        actionVolumeFilterMedian->setText(QApplication::translate("MainWindow", "Median...", 0, QApplication::UnicodeUTF8));
        actionVolumeFilterConvolve->setText(QApplication::translate("MainWindow", "Convolve...", 0, QApplication::UnicodeUTF8));
        actionVolumeFilterGradient->setText(QApplication::translate("MainWindow", "Gradient...", 0, QApplication::UnicodeUTF8));
        actionCloseVolume->setText(QApplication::translate("MainWindow", "Close Volume", 0, QApplication::UnicodeUTF8));
        actionCloseSurface->setText(QApplication::translate("MainWindow", "Close Surface", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        actionCloseSurface->setToolTip(QApplication::translate("MainWindow", "Close Surface", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        actionCloseROI->setText(QApplication::translate("MainWindow", "Close ROI", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        actionCloseROI->setToolTip(QApplication::translate("MainWindow", "Close ROI", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        actionClosePointSet->setText(QApplication::translate("MainWindow", "Close Point Set", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        actionClosePointSet->setToolTip(QApplication::translate("MainWindow", "Close Point Set", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        actionVolumes->setText(QApplication::translate("MainWindow", "Volumes", 0, QApplication::UnicodeUTF8));
        actionSurfaces->setText(QApplication::translate("MainWindow", "Surfaces", 0, QApplication::UnicodeUTF8));
        actionVolumeFilterSobel->setText(QApplication::translate("MainWindow", "Sobel", 0, QApplication::UnicodeUTF8));
        actionRunCommand->setText(QApplication::translate("MainWindow", "Run Command...", 0, QApplication::UnicodeUTF8));
        actionLoadCommand->setText(QApplication::translate("MainWindow", "Load Command...", 0, QApplication::UnicodeUTF8));
        actionShowCommandConsole->setText(QApplication::translate("MainWindow", "Show Command Console", 0, QApplication::UnicodeUTF8));
        actionLoadTrack->setText(QApplication::translate("MainWindow", "Load Track...", 0, QApplication::UnicodeUTF8));
        actionCloseTrack->setText(QApplication::translate("MainWindow", "Close Track", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        actionCloseTrack->setToolTip(QApplication::translate("MainWindow", "Close Track", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        actionShowSlices->setText(QApplication::translate("MainWindow", "Show Slices (3D View)", 0, QApplication::UnicodeUTF8));
        actionShowSlices->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+S", 0, QApplication::UnicodeUTF8));
        actionLoadTrackVolume->setText(QApplication::translate("MainWindow", "Load Track Volume...", 0, QApplication::UnicodeUTF8));
        actionIncreaseOpacity->setText(QApplication::translate("MainWindow", "Increase Opacity", 0, QApplication::UnicodeUTF8));
        actionIncreaseOpacity->setShortcut(QApplication::translate("MainWindow", "Alt+S", 0, QApplication::UnicodeUTF8));
        actionDecreaseOpacity->setText(QApplication::translate("MainWindow", "Decrease Opacity", 0, QApplication::UnicodeUTF8));
        actionDecreaseOpacity->setShortcut(QApplication::translate("MainWindow", "Alt+A", 0, QApplication::UnicodeUTF8));
        actionIntensityProject->setText(QApplication::translate("MainWindow", "Create Intensity Projection Map", 0, QApplication::UnicodeUTF8));
        actionTimeCourse->setText(QApplication::translate("MainWindow", "Show Time Course", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        actionTimeCourse->setToolTip(QApplication::translate("MainWindow", "View Time Course", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        actionPlot->setText(QApplication::translate("MainWindow", "Plot FSGD Data...", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        actionPlot->setToolTip(QApplication::translate("MainWindow", "Plot FSGD Data", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        tabWidgetControlPanel->setTabText(tabWidgetControlPanel->indexOf(tabVolume), QApplication::translate("MainWindow", "Volumes", 0, QApplication::UnicodeUTF8));
        tabWidgetControlPanel->setTabText(tabWidgetControlPanel->indexOf(tabSurface), QApplication::translate("MainWindow", "Surfaces", 0, QApplication::UnicodeUTF8));
        tabWidgetControlPanel->setTabText(tabWidgetControlPanel->indexOf(tabROI), QApplication::translate("MainWindow", "ROIs", 0, QApplication::UnicodeUTF8));
        tabWidgetControlPanel->setTabText(tabWidgetControlPanel->indexOf(tabPointSet), QApplication::translate("MainWindow", "Point Sets", 0, QApplication::UnicodeUTF8));
        tabWidgetControlPanel->setTabText(tabWidgetControlPanel->indexOf(tabTrack), QApplication::translate("MainWindow", "Tracks", 0, QApplication::UnicodeUTF8));
        QTreeWidgetItem *___qtreewidgetitem = treeWidgetCursorInfo->headerItem();
        ___qtreewidgetitem->setText(1, QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        QTreeWidgetItem *___qtreewidgetitem1 = treeWidgetMouseInfo->headerItem();
        ___qtreewidgetitem1->setText(1, QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        ___qtreewidgetitem1->setText(0, QApplication::translate("MainWindow", "Mouse", 0, QApplication::UnicodeUTF8));
        menuFile->setTitle(QApplication::translate("MainWindow", "File", 0, QApplication::UnicodeUTF8));
        menuRecentFiles->setTitle(QApplication::translate("MainWindow", "Recent Files", 0, QApplication::UnicodeUTF8));
        menuEdit->setTitle(QApplication::translate("MainWindow", "Edit", 0, QApplication::UnicodeUTF8));
        menuView->setTitle(QApplication::translate("MainWindow", "View", 0, QApplication::UnicodeUTF8));
        menuViewport_Layout->setTitle(QApplication::translate("MainWindow", "Viewport Layout", 0, QApplication::UnicodeUTF8));
        menuLayer->setTitle(QApplication::translate("MainWindow", "Layer", 0, QApplication::UnicodeUTF8));
        menuAction->setTitle(QApplication::translate("MainWindow", "Action", 0, QApplication::UnicodeUTF8));
        menuTools->setTitle(QApplication::translate("MainWindow", "Tools", 0, QApplication::UnicodeUTF8));
        menuVolume_Fiilter->setTitle(QApplication::translate("MainWindow", "Volume Filter", 0, QApplication::UnicodeUTF8));
        menuHelp->setTitle(QApplication::translate("MainWindow", "Help", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

