/*
 * Original Author: Dan Ginsburg (@ Children's Hospital Boston)
 * CVS Revision Info:
 *    $Author: nicks $
 *    $Date: 2011/03/02 00:04:31 $
 *    $Revision: 1.4 $
 *
 * Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
 *
 * Terms and conditions for use, reproduction, distribution and contribution
 * are found in the 'FreeSurfer Software License Agreement' contained
 * in the file 'LICENSE' found in the FreeSurfer distribution, and here:
 *
 * https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
 *
 * Reporting: freesurfer@nmr.mgh.harvard.edu
 *
 */
#ifndef __MainWindow__
#define __MainWindow__

#include <wx/string.h>
#include <vector>

extern "C"
{
#include "mrisurf.h"
}

/**
@file
Subclass of MainWindowBase, which is generated by wxFormBuilder.
*/

#include "MainWindowBase.h"

class RenderPanel;
class DecimatePanel;
class wxPanel;

/** Implementing MainWindowBase */
class MainWindow : public MainWindowBase
{
protected:
    // Handlers for MainWindowBase events.
    void OnFileOpen( wxCommandEvent& event );
    void OnFileExit( wxCommandEvent& event );
    void OnFileSave( wxCommandEvent& event );
    void OnFileSaveAs( wxCommandEvent& event );
    void OnAbout( wxCommandEvent& event );
    void OnClose( wxCloseEvent& event );

    void CommandLoadSurface( const wxArrayString& sa );
    void CommandScreenCapture( const wxArrayString& sa );
    void CommandDecimationLevel( const wxArrayString& sa );
    void CommandCurvature( const wxArrayString& sa );
    void CommandFileSave( const wxArrayString& sa );
    void CommandCameraRotate( const wxArrayString& sa );

    void LoadSurface(const wxString& filePath);


public:
    /// Constructor
    MainWindow( wxWindow* parent );

    /// Add a script command to run on startup
    void AddScript( const wxArrayString& script );

    /// Run a script established from the command-line (or elsewhere)
    void RunScript();

    /// Handle updates to the camera
    void HandleCameraUpdate();
        
    /// Original MRIS surface
    MRI_SURFACE *m_origSurface;

    /// Decimate Panel
    DecimatePanel *m_decimatePanel;

    /// Render Panel
    RenderPanel *m_renderPanel;

    /// Render Panel Holder
    wxPanel *m_renderPanelHolder;

    /// Current File Path
    wxString m_currentFilePath;

    /// Last load directory
    wxString m_lastLoadDir;

    /// Last save directory
    wxString m_lastSaveDir;

    /// Script commands
    std::vector<wxArrayString> m_scripts;

};

#endif // __MainWindow__
