sudo: required

language: cpp

compiler: gcc

cache:
  - apt
  - ccache

matrix:
  include:
  - os: osx
  - os: linux

addons:
  apt:
    packages:
     - build-essential
     - libtool
     - automake
     - gfortran
     - libglu1-mesa-dev
     - libfreetype6-dev
     - uuid-dev
     - libxmu-dev
     - libxmu-headers
     - libxi-dev
     - libx11-dev
     - libxt-dev
     - libxaw7-dev
     - liblapack-dev
     - tcsh
     - curl
     - git
     - libxml2-utils

before_install:
  # on osx use brew to install autotools and compiler
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update ;
      brew install libtool ;
      brew install automake ;
      brew postinstall automake ;
    fi
  # workaround to make install gcc work (first uninstall conflicting oclint)
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew cask uninstall oclint ;
      brew install gcc49 ;
      brew postinstall gcc49 ;
    fi

install:
  # install pre-built packages needed to compile FreeSurfer
  - ./travis/packages.sh || travis_terminate 1

script:
  # configure and compile freesurfer
  - travis_wait 40 ./travis/build.sh || travis_terminate 1

after_failure:
  - tail -n 100 build.log
