sudo: required

language: cpp

compiler: gcc

os: linux

cache:
  - apt
  - ccache

env:
  matrix:
  # Compile Only:
  - TESTS=""
  # Autorecon1:
  - TESTS="mri_convert mri_add_xform_to_header talairach_avi talairach_afd mri_normalize mri_watershed"
  # Autorecon2:
  - TESTS="mri_cc mri_mask mri_segment mri_edit_wm_with_aseg mri_pretess mri_fill mri_tesellate mris_inflate"
  # Autorecon3:
  - TESTS="mris_ca_label"
  # Misc
  - TESTS="utils"

addons:
  apt:
    packages:
     - build-essential
     - libtool
     - automake
     - gfortran
     - libglu1-mesa-dev
     - libfreetype6-dev
     - uuid-dev
     - libxmu-dev
     - libxmu-headers
     - libxi-dev
     - libx11-dev
     - libxt-dev
     - libxaw7-dev
     - liblapack-dev
     - tcsh
     - curl
     - git
     - libxml2-utils

before_install:
  # Needs recent git-annex to be able to get -J3 --metadata ; fi
  - if [[ "$TESTS" != "" ]]; then bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh) ; fi
  - if [[ "$TESTS" != "" ]]; then travis_retry sudo apt-get update -qq ; fi
  - if [[ "$TESTS" != "" ]]; then travis_retry sudo apt-get install git-annex-standalone ; fi
  - if [[ "$TESTS" != "" ]]; then git fetch origin git-annex ; fi
  - if [[ "$TESTS" != "" ]]; then git remote add datasrc http://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/repo/annex.git ; fi
  - if [[ "$TESTS" != "" ]]; then git fetch datasrc git-annex ; fi
  - if [[ "$TESTS" != "" ]]; then git annex get -J3 --metadata fstags=makecheck . ; fi

install:
  # Install library packages needed to compile FreeSurfer
  - curl -O ftp://surfer.nmr.mgh.harvard.edu/pub/dist/fs_supportlibs/prebuilt/centos6_x86_64/centos6-x86_64-packages.tar.gz
  - tar -xzf centos6-x86_64-packages.tar.gz 
  - rm centos6-x86_64-packages.tar.gz 
  - cd centos6-x86_64-packages 
  - ./setup.sh
  - cd ..

script:
  # configure and build freesurfer
  - ./setup_configure
  - ./configure --prefix=/usr/local/freesurfer/dev --with-pkgs-dir=${PWD}/centos6-x86_64-packages --disable-Werror --disable-GUI-build
  - travis_wait 40 ./travis_make.sh || travis_terminate 1
  # run tests
  - if [[ "$TESTS" != "" ]]; then travis_wait 60 ./run_selected_tests ; fi

after_failure:
  - tail -n 200 build.log
  
