sudo: required

dist: trusty
language: cpp

cache:
  - apt
  - ccache

matrix:
  include:
    - os: linux
    - os: osx

addons:
  apt:
    packages:
      - gfortran
      - libxi-dev
      - liblapack-dev
      - python3.5-dev
      - tcsh
      - curl
      - git

install:
  - travis/packages.sh

script:
  - travis/build.sh
