sudo: required

language: cpp

compiler: gcc

os: linux

cache:
 - apt
 - ccache

env:
 matrix:
   - TESTS="mri_ca_label"
#   - TESTS="mris_* histo_*"
#   - TESTS="mri_[abcdef]*"
#   - TESTS="jpeg tiff expat utils"
addons:
  apt:
    packages:
     - build-essential
     - libtool
     - automake
     - gfortran
     - libglu1-mesa-dev
     - libfreetype6-dev
     - uuid-dev
     - libxmu-dev
     - libxmu-headers
     - libxi-dev
     - libx11-dev
     - libxt-dev
     - libxaw7-dev
     - liblapack-dev
     - tcsh
     - curl
     - git
     - libxml2-utils

before_install:
  # Needs recent git-annex to be able to get -J3 --metadata
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install git-annex-standalone
  - git fetch origin git-annex
  - git remote add datasrc http://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/repo/annex.git
  - git fetch datasrc git-annex

install:
  - git annex get -J3 --metadata fstags=makecheck .
  - curl -O ftp://surfer.nmr.mgh.harvard.edu/pub/dist/fs_supportlibs/prebuilt/centos6_x86_64/centos6-x86_64-packages.tar.gz
  - tar -xzf centos6-x86_64-packages.tar.gz 
  - rm centos6-x86_64-packages.tar.gz 
  - cd centos6-x86_64-packages 
  - ./setup.sh
  - cd ..

script:
  - ./setup_configure
  - ./configure --prefix=/usr/local/freesurfer/dev --with-pkgs-dir=${PWD}/centos6-x86_64-packages --disable-Werror --disable-GUI-build
  - travis_wait 40 ./travis_make.sh
  - tail build.log
  - ./run_selected_tests

after_failure:
  
