sudo: required

dist: trusty
language: cpp
compiler: gcc

cache:
  - apt
  - ccache

matrix:
  include:
    - os: linux
    - os: osx

addons:
  apt:
    packages:
      - gfortran
      - libxi-dev
      - liblapack-dev
      - python3.5-dev
      - tcsh
      - curl
      - git
  homebrew:
    packages:
      - gcc
      - glib

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then base=centos7 ; else base=osx10.11 ; fi
  - curl --connect-timeout 8 --retry 5 -O http://surfer.nmr.mgh.harvard.edu/pub/data/fspackages/prebuilt/${base}-packages.tar.gz
  - tar -xzf ${base}-packages.tar.gz

script:
  - cmake . -DFS_PACKAGES_DIR=packages -DBUILD_GUIS=OFF
  - make -j4
