sudo: required

language: cpp

compiler: gcc

cache:
  - apt
  - ccache

matrix:
  include:
  - os: osx
  - os: linux

addons:
  apt:
    packages:
     - build-essential
     - libtool
     - automake
     - gfortran
     - libglu1-mesa-dev
     - libfreetype6-dev
     - uuid-dev
     - libxmu-dev
     - libxmu-headers
     - libxi-dev
     - libx11-dev
     - libxt-dev
     - libxaw7-dev
     - liblapack-dev
     - tcsh
     - curl
     - git
     - libxml2-utils

before_install:
  # on osx use brew to install autotools and compiler
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update ;
      brew install libtool ;
      brew install automake ;
      brew postinstall automake ;
    fi
  # workaround to make install gcc work (first uninstall conflicting oclint)
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew cask uninstall oclint ;
      brew install gcc49 ;
      brew postinstall gcc49 ;
    fi

install:
  # Install library packages needed to compile FreeSurfer
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl --verbose --connect-timeout 8 --retry 60 --retry-delay 3 -O http://surfer.nmr.mgh.harvard.edu/pub/dist/fs_supportlibs/prebuilt/centos6_x86_64/centos6-x86_64-packages.tar.gz || travis_terminate 1 ;
      tar -xzf centos6-x86_64-packages.tar.gz  ;
      rm centos6-x86_64-packages.tar.gz  ;
      cd centos6-x86_64-packages  ;
      ./setup.sh ;
      cd .. ;
    fi
  # different package on osx
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then
      mkdir osx-lion-packages ;
      cd osx-lion-packages ;
      curl --verbose --connect-timeout 8 --retry 60 --retry-delay 3 -O http://surfer.nmr.mgh.harvard.edu/pub/dist/fs_supportlibs/prebuilt/OSX/osx-lion-packages.tar.gz || travis_terminate 1 ;
      tar -xzf osx-lion-packages.tar.gz ;
      rm osx-lion-packages.tar.gz ;
      cd .. ;
    fi

script:
  # configure and build freesurfer
  - ./setup_configure
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./configure --prefix=/usr/local/freesurfer/dev --with-pkgs-dir=${PWD}/centos6-x86_64-packages --disable-Werror --disable-GUI-build ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then
      ./configure --prefix=/usr/local/freesurfer/dev --with-pkgs-dir=${PWD}/osx-lion-packages       --disable-Werror --disable-GUI-build  F77=/usr/local/bin/gfortran-4.9 CC=/usr/local/bin/gcc-4.9 CXX=/usr/local/bin/g++-4.9 ;
    fi
  - travis_wait 40 ./travis_make.sh || travis_terminate 1

after_failure:
  - tail -n 200 build.log
