sudo: required

language: cpp
compiler: gcc

cache:
  - apt
  - ccache

matrix:
  include:
    - os: osx
    - os: linux

addons:
  apt:
    packages:
      - build-essential
      - gfortran
      - libglu1-mesa-dev
      - libxmu-dev
      - libxmu-headers
      - libxi-dev
      - libx11-dev
      - libxt-dev
      - liblapack-dev
      - tcsh
      - curl
      - git

install:
  - travis/packages.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then
      brew cask uninstall oclint ;
      brew install gcc5 ;
      export CC=/usr/local/bin/gcc-5 ;
      export CXX=/usr/local/bin/g++-5 ;
      export FC=/usr/local/bin/gfortran-5 ;
    fi

script:
  - cmake . -DFS_PACKAGES_DIR="packages" && make
