if(CMAKE_C_COMPILER MATCHES cl)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /D _CRT_SECURE_NO_WARNINGS /wd 4244")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /D _CRT_SECURE_NO_WARNINGS /wd 4244")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /FORCE:MULTIPLE")
    set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} /FORCE:MULTIPLE")
	set(CMAKE_ALLOW_LOOSE_LOOP_CONSTRUCTS TRUE)
endif()
INCLUDE (graphics.cmake)
set (FREESURFER_INCLUDE_ROOT ${freesurfer_SOURCE_DIR}/include)
set (INCLUDE_DIR_TOP  
${freesurfer_SOURCE_DIR}
${FREESURFER_INCLUDE_ROOT}
${FREESURFER_INCLUDE_ROOT}/dicom
${FREESURFER_INCLUDE_ROOT}/fs_vnl
${FREESURFER_INCLUDE_ROOT}/NrrdIO
${FREESURFER_INCLUDE_ROOT}/pixrect
${FREESURFER_INCLUDE_ROOT}/sys
${freesurfer_SOURCE_DIR}/unix
${FREESURFER_INCLUDE_ROOT}/topology
${FREESURFER_INCLUDE_ROOT}/xview
)
include_directories (BEFORE ${INCLUDE_DIR_TOP})
INCLUDE(gnuwin32.cmake)
include_directories (BEFORE ${GNU_INCLUDE_DIR})
INCLUDE(vxl.cmake)
include_directories (${VXL_INCLUDES})
INCLUDE(minc.cmake)
include_directories (${MINC_INCLUDE_DIR})

SET (FS_AUX_LIBS 
${TIFF_LIBRARIES} 
${JPEG_LIBRARIES} 
${ZLIB_LIBRARIES} 
${MINC_LIBRARIES} 
${TCL_LIBRARIES} 
${VXL_LIBS} 
${GL_LIBS} 
${GLUT_LIBS} 
${VTK_LIBRARIES} 
${ITK_LIBS} 
${KWWidgets_LIBRARIES}
${LIBXML2_LIBRARIES} 
${EXPAT_LIBRARIES}
)

