FIND_PACKAGE(ITK)
IF(ITK_FOUND)
   INCLUDE(${ITK_USE_FILE})
ENDIF(ITK_FOUND)

FIND_PACKAGE(VTK)
IF(VTK_FOUND) 
   INCLUDE(${VTK_USE_FILE})
ENDIF(VTK_FOUND)

FIND_PACKAGE(KWWidgets)
IF(KWWidgets_FOUND)
	INCLUDE(${KWWidgets_USE_FILE})
ENDIF(KWWidgets_FOUND)

FIND_PACKAGE (TCL)
FIND_PACKAGE (OPENGL)

SET (VTK_LIBS
	VTKCommon
)

SET (ITK_LIBS
	ITKCommon
	ITKIO
)

FIND_LIBRARY(TIX_LIBRARY
NAMES blt24 BLT24 blt23 BLT23 BLT blt
PATHS ${TCLTK_POSSIBLE_LIB_PATHS}
)

FIND_LIBRARY(BLT_LIBRARY
NAMES tix83 tix82 tix81 tix80 tix
PATHS ${TCLTK_POSSIBLE_LIB_PATHS}
)

SET (GRAPH_INCLUDES
	${VTK_INCLUDE_DIRS}
	${KWWidgets_INCLUDE_DIRS}
	${ITK_INCLUDE_DIRS}
	${TCL_INCLUDE_PATH}
	${OPENGL_INCLUDE_DIR}
	${BLT_LIBRARY}
	${TIX_LIBRARY}
)

