#!/bin/bash
#
# Tests runner for a selection of tests as specified by TESTS env
# variable which should contain space separated collection of entries of
# syntax
#  DIRECTORYGLOB[:test1[,test2,...]]
# e.g. smth as simple as
#  TESTS="expat mri_*"
# or
#  TESTS="expat:runtestspp tiff"
# etc
#
# Directories which have no 'make check' available would be skipped

set -eu
failed=0; 

# Skip some tests that wont pass on travis platform
# but should pass on Martinos build machine.
export SKIP_LIBG2C_TEST=1

# Should come from env var
TESTS=${TESTS:-}
outfile=$(mktemp)

for TEST in ${TESTS}; do    
    tests=$(echo "$TEST" | sed -n -e 's,^[^:]*\(:\(.*\)\)$,\2,gp' | sed -e 's/,/ /g');
    testdir=${TEST#:*};
    [ -z "$tests" ] && testsstr='' || testsstr="TESTS=\"$tests\""
    # Verify that there is a check rule
    make -n -C $testdir -n check >/dev/null 2>&1 || { echo "Not testing $testdir -- no check rule"; continue; }
    echo -n "Testing $testdir/ $testsstr: ";
    t0=$(date -u +%s)
    make -C $testdir check -j4  $testsstr 1>|$outfile 2>&1 && ok=1 || ok=0
    t1=$(date -u +%s)
    tdiff=$(($t1-$t0))
    diff=$(date -u -d @"$tdiff" +'[%-Hh %-Mm %-Ss] ')
    [ $ok = 1 ] &&   echo -e "\rPASS in $diff $testdir/ $testsstr" \
                || { echo -e "\rFAIL in $diff $testdir/ $testsstr"; cat $outfile; failed=1; }
done

exit $failed

