#!/bin/tcsh -f

#
# test_mris_convert
#
# execute mris_convert and check results against expected results
#
# Original Author: Nick Schmansky
# CVS Revision Info:
#    $Author: nicks $
#    $Date: 2011/05/02 21:02:43 $
#    $Revision: 1.5 $
#
# Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
#
# Terms and conditions for use, reproduction, distribution and contribution
# are found in the 'FreeSurfer Software License Agreement' contained
# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
#
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
#
# Reporting: freesurfer@nmr.mgh.harvard.edu
#
# General inquiries: freesurfer@nmr.mgh.harvard.edu
# Bug reports: analysis-bugs@nmr.mgh.harvard.edu
#

set VERSION='$Id: test_mris_convert,v 1.5 2011/05/02 21:02:43 nicks Exp $'

umask 002

#
# extract testing data, reuse another tests data
#
gunzip -c ../mris_expand/testdata.tar.gz | tar xvf -

#
# run mris_convert, converting to ascii, gifti, mgh and vtk, then back to binary
#

set cmd=(./mris_convert lh.white lh.white.asc)
echo ""
echo $cmd
echo $cmd >& test_mris_convert.log
echo ""
$cmd >>& test_mris_convert.log
if ($status != 0) then
  echo "mris_convert FAILED"
  exit 1
endif

set cmd=(./mris_convert lh.white.asc lh.new-white)
echo ""
echo $cmd
echo $cmd >& test_mris_convert.log
echo ""
$cmd >>& test_mris_convert.log
if ($status != 0) then
  echo "mris_convert FAILED"
  exit 1
endif

set cmd=(./mris_convert lh.white lh.white.gii)
echo ""
echo $cmd
echo $cmd >& test_mris_convert.log
echo ""
$cmd >>& test_mris_convert.log
if ($status != 0) then
  echo "mris_convert FAILED"
  exit 1
endif

set cmd=(./mris_convert lh.white.gii lh.gifti-white)
echo ""
echo $cmd
echo $cmd >& test_mris_convert.log
echo ""
$cmd >>& test_mris_convert.log
if ($status != 0) then
  echo "mris_convert FAILED"
  exit 1
endif

set cmd=(./mris_convert lh.white lh.white.vtk)
echo ""
echo $cmd
echo $cmd >& test_mris_convert.log
echo ""
$cmd >>& test_mris_convert.log
if ($status != 0) then
  echo "mris_convert FAILED"
  exit 1
endif

set cmd=(./mris_convert lh.white.vtk lh.vtk-white)
echo ""
echo $cmd
echo $cmd >& test_mris_convert.log
echo ""
$cmd >>& test_mris_convert.log
if ($status != 0) then
  echo "mris_convert FAILED"
  exit 1
endif

set cmd=(./mris_convert -c lh.thickness lh.white lh.new-thickness.asc)
echo ""
echo $cmd
echo $cmd >& test_mris_convert.log
echo ""
$cmd >>& test_mris_convert.log
if ($status != 0) then
  echo "mris_convert FAILED"
  exit 1
endif

set cmd=(./mris_convert -c lh.thickness lh.white lh.thickness.mgh)
echo ""
echo $cmd
echo $cmd >& test_mris_convert.log
echo ""
$cmd >>& test_mris_convert.log
if ($status != 0) then
  echo "mris_convert FAILED"
  exit 1
endif

set cmd=(./mris_convert -c lh.thickness.mgh lh.white lh.mgh-thickness.asc)
echo ""
echo $cmd
echo $cmd >& test_mris_convert.log
echo ""
$cmd >>& test_mris_convert.log
if ($status != 0) then
  echo "mris_convert FAILED"
  exit 1
endif

set cmd=(./mris_convert -c lh.thickness lh.white lh.thickness.gii)
echo ""
echo $cmd
echo $cmd >& test_mris_convert.log
echo ""
$cmd >>& test_mris_convert.log
if ($status != 0) then
  echo "mris_convert FAILED"
  exit 1
endif

set cmd=(./mris_convert -c lh.thickness lh.white lh.white.thickness.vtk)
echo ""
echo $cmd
echo $cmd >& test_mris_convert.log
echo ""
$cmd >>& test_mris_convert.log
if ($status != 0) then
  echo "mris_convert FAILED"
  exit 1
endif

set cmd=(./mris_convert -c lh.thickness.asc lh.white lh.new-thickness)
echo ""
echo $cmd
echo $cmd >& test_mris_convert.log
echo ""
$cmd >>& test_mris_convert.log
if ($status != 0) then
  echo "mris_convert FAILED"
  exit 1
endif

set cmd=(./mris_convert -c lh.new-thickness lh.white lh.newer-thickness.asc)
echo ""
echo $cmd
echo $cmd >& test_mris_convert.log
echo ""
$cmd >>& test_mris_convert.log
if ($status != 0) then
  echo "mris_convert FAILED"
  exit 1
endif

set cmd=(./mris_convert -c lh.thickness.gii lh.white.gii \
    lh.gifti-thickness.asc)
echo ""
echo $cmd
echo $cmd >& test_mris_convert.log
echo ""
$cmd >>& test_mris_convert.log
if ($status != 0) then
  echo "mris_convert FAILED"
  exit 1
endif

set cmd=(./mris_convert -c lh.white.thickness.vtk lh.white.vtk \
    lh.vtk-thickness.asc)
echo ""
echo $cmd
echo $cmd >& test_mris_convert.log
echo ""
$cmd >>& test_mris_convert.log
if ($status != 0) then
  echo "mris_convert FAILED"
  exit 1
endif

#
# compare expected results with actual (produced) results
#

set REF=(lh.white)
set TST=(lh.new-white)
set cmd=(../mris_diff/mris_diff --debug --thresh 0.0001 $REF $TST);
echo ""
echo $cmd
echo $cmd >>& test_mris_convert.log
$cmd >>& test_mris_convert.log
set diff_status=$status
if ($diff_status != 0) then
  echo "$cmd FAILED (exit status=$diff_status)"
  exit 1
endif

set REF=(lh.white)
set TST=(lh.gifti-white)
set cmd=(../mris_diff/mris_diff --debug --thresh 0.0001 $REF $TST);
echo ""
echo $cmd
echo $cmd >>& test_mris_convert.log
$cmd >>& test_mris_convert.log
set diff_status=$status
if ($diff_status != 0) then
  echo "$cmd FAILED (exit status=$diff_status)"
  exit 1
endif

set REF=(lh.white)
set TST=(lh.vtk-white)
set cmd=(../mris_diff/mris_diff --debug --no-check-nxyz \
    --thresh 0.0001 $REF $TST);
echo ""
echo $cmd
echo $cmd >>& test_mris_convert.log
$cmd >>& test_mris_convert.log
set diff_status=$status
if ($diff_status != 0) then
  echo "$cmd FAILED (exit status=$diff_status)"
  exit 1
endif

set REF=(lh.thickness.asc)
set TST=(lh.new-thickness.asc)
set cmd=(diff $REF $TST);
echo ""
echo $cmd
echo $cmd >>& test_mris_convert.log
$cmd >>& test_mris_convert.log
set diff_status=$status
if ($diff_status != 0) then
  echo "$cmd FAILED (exit status=$diff_status)"
  exit 1
endif

set REF=(lh.thickness.asc)
set TST=(lh.mgh-thickness.asc)
set cmd=(diff $REF $TST);
echo ""
echo $cmd
echo $cmd >>& test_mris_convert.log
$cmd >>& test_mris_convert.log
set diff_status=$status
if ($diff_status != 0) then
  echo "$cmd FAILED (exit status=$diff_status)"
  exit 1
endif

set REF=(lh.new-thickness.asc)
set TST=(lh.newer-thickness.asc)
set cmd=(diff $REF $TST);
echo ""
echo $cmd
echo $cmd >>& test_mris_convert.log
$cmd >>& test_mris_convert.log
set diff_status=$status
if ($diff_status != 0) then
  echo "$cmd FAILED (exit status=$diff_status)"
  exit 1
endif

set REF=(lh.thickness.asc)
set TST=(lh.gifti-thickness.asc)
set cmd=(diff $REF $TST);
echo ""
echo $cmd
echo $cmd >>& test_mris_convert.log
$cmd >>& test_mris_convert.log
set diff_status=$status
if ($diff_status != 0) then
  echo "$cmd FAILED (exit status=$diff_status)"
  exit 1
endif

set REF=(lh.thickness.asc)
set TST=(lh.vtk-thickness.asc)
set cmd=(diff $REF $TST);
echo ""
echo $cmd
echo $cmd >>& test_mris_convert.log
$cmd >>& test_mris_convert.log
set diff_status=$status
if ($diff_status != 0) then
  echo "$cmd FAILED (exit status=$diff_status)"
  exit 1
endif

#
# cleanup
#
end:
rm -f lh.*

echo ""
echo "test_mris_convert passed all tests"
exit 0
