% $Id: unwarp_scanners_table.m,v 1.1 2003/07/24 21:24:18 ebeth Exp $
% 
% Ugh, this is tricky - because there's model names signa and genesis
% signa, and there's station name bay1 and bay1ow0, etc.  So some
% {{'cell', 'arrays'}}...  And note many scanners don't set their
% ScannerSerialNo tag.  -ebeth

function m = unwarp_scanners_table()

global GRADWARPPATH;
global TABLE;
unwarp_init_globals(0); % 0 = called by script - probably not!

m(1) = struct(...
    'nickname','crm',...
    'Manufacturer','ge medical systems',...
    'ManufacturersModelName',{{'signa','genesis signa'}},...
    'ScannerSerialNo',...
    {{...
	'0000000000345649',... % Duke
	'0000ONGWOOD15MR'...   % BWH
	}},...
    'InstitutionStation',...
    {{...
	'anon mr6cow'...                  % Duke
	'imaging center bay1 bay1ow0',... % MGH Bay1
	'imaging center bay1 bay1',...    % MGH Bay1
	'cni ms scanner boston bwow1',... % BWH
	}},...
    'filename',sprintf('%s/crm.gwv',GRADWARPPATH)...
    );

m(2) = struct(...
    'nickname','brm',...
    'Manufacturer','ge medical systems',...
    'ManufacturersModelName',{{'signa','genesis signa'}},...
    'ScannerSerialNo',...
    {{...
	}},...
    'InstitutionStation',...
    {{...
	'vamcsd mrs1'                     % UCSD
        }},...
    'filename',sprintf('%s/brm.gwv',GRADWARPPATH)...
    );

m(3) = struct(...
    'nickname','sonata',...
    'Manufacturer','siemens',...
    'ManufacturersModelName',{{'sonata','trio'}},...
    'ScannerSerialNo',...
    {{...
	'21913'...                        % MGH-Bay 2
	}},...
    'InstitutionStation',...
    {{...
        }},...
    'filename',sprintf('%s/sonata.gwv',GRADWARPPATH)...
    );

m(4) = struct(...
    'nickname','trio',...
    'Manufacturer','siemens',...
    'ManufacturersModelName',{{'sonata','trio'}},...
    'ScannerSerialNo',...
    {{...
	}},...
    'InstitutionStation',...
    {{...
        }},...
    'filename',sprintf('%s/sonata.gwv',GRADWARPPATH)...
    );

m(5) = struct(...
    'nickname','allegra',...
    'Manufacturer','siemens',...
    'ManufacturersModelName',{{'allegra'}},...
    'ScannerSerialNo',...
    {{...
	}},...
    'InstitutionStation',...
    {{...
        }},...
    'filename',sprintf('%s/allegra.gwv',GRADWARPPATH)...
    );

save(TABLE);
return


