#############################################################################
# Makefile for building: testVolumeHistogram
# Generated by qmake (1.07a) (Qt 3.3.3) on: Sat Nov 27 17:57:06 2004
# Project:  testVolumeHistogram.pro
# Template: app
# Command: $(QMAKE) -o test_VolumeHistogram.mak testVolumeHistogram.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT -g
CXXFLAGS = -pipe -Wall -W -O2  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT -g
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/local/qt/mkspecs/default -I. -I../include -I/usr/pubsw/include -I. -I$(QTDIR)/include
LINK     = g++
LFLAGS   =  -Wl,-rpath,$(QTDIR)/lib
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib /home/kteich/fsdev/trunk/dev/utils/libutils.a /home/kteich/fsdev/trunk/dev/rgb/librgb.a /home/kteich/fsdev/trunk/dev/unix/libunix.a /home/kteich/fsdev/trunk/dev/dicom/libdicom.a /home/kteich/fsdev/trunk/dev/hipsstubs/libhipsstubs.a -L/usr/pubsw/lib -lBLT -ltix8.1.8.3 -ltk -ltcl -lglut -lSM -lICE -lXmu -lXi -lGLU -lGL -L/usr/X11R6/lib -lvolume_io -lminc -lnetcdf -ljpeg -ltiff -lcrypt -lz -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = Array2.h \
		Broadcaster.h \
		DataCollection.h \
		DataManager.h \
		DebugReporter.h \
		IDTracker.h \
		InputState.h \
		Layer.h \
		LinePool.h \
		Listener.h \
		Matrix44.h \
		Path.h \
		PathManager.h \
		Point2.h \
		Point3.h \
		PointList3.h \
		PreferencesManager.h \
		QTScubaWidget.h \
		QtVolumeHistogram.h \
		ScubaColorLUT.h \
		ScubaDataCollectionFactory.h \
		ScubaFrame.h \
		ScubaGlobalPreferences.h \
		Scuba-impl.h \
		ScubaLayer2DMRI.h \
		ScubaLayer2DMRIS.h \
		ScubaLayerFactory.h \
		ScubaROI.h \
		ScubaROIVolume.h \
		ScubaToolState.h \
		ScubaTransform.h \
		ScubaView.h \
		ScubaWindowToRASTranslator.h \
		ShortestPathFinder.h \
		string_fixed.h \
		SurfaceCollection.h \
		TclCommandManager.h \
		TclProgressDisplayManager.h \
		Timer.h \
		Transform44.h \
		UndoManager.h \
		Utilities.h \
		VectorOps.h \
		View.h \
		ViewState.h \
		Volume3.h \
		VolumeCollection.h \
		WindowFrame.h
SOURCES = Array2.cpp \
		Broadcaster.cpp \
		DataCollection.cpp \
		DataManager.cpp \
		DebugReporter.cpp \
		IDTracker.cpp \
		InputState.cpp \
		Layer.cpp \
		Listener.cpp \
		Matrix44.cpp \
		Path.cpp \
		PathManager.cpp \
		Point2.cpp \
		Point3.cpp \
		PointList3.cpp \
		PreferencesManager.cpp \
		QTScubaWidget.cpp \
		QtVolumeHistogram.cpp \
		ScubaColorLUT.cpp \
		ScubaDataCollectionFactory.cpp \
		ScubaFrame.cpp \
		ScubaGlobalPreferences.cpp \
		ScubaLayer2DMRI.cpp \
		ScubaLayer2DMRIS.cpp \
		ScubaLayerFactory.cpp \
		ScubaROI.cpp \
		ScubaROIVolume.cpp \
		ScubaToolState.cpp \
		ScubaTransform.cpp \
		ScubaView.cpp \
		ScubaWindowToRASTranslator.cpp \
		ShortestPathFinder.cpp \
		SurfaceCollection.cpp \
		TclCommandManager.cpp \
		TclProgressDisplayManager.cpp \
		test_VolumeHistogram.cpp \
		Timer.cpp \
		Transform44.cpp \
		UndoManager.cpp \
		Utilities.cpp \
		VectorOps.cpp \
		View.cpp \
		ViewState.cpp \
		Volume3.cpp \
		VolumeCollection.cpp \
		WindowFrame.cpp
OBJECTS = Array2.o \
		Broadcaster.o \
		DataCollection.o \
		DataManager.o \
		DebugReporter.o \
		IDTracker.o \
		InputState.o \
		Layer.o \
		Listener.o \
		Matrix44.o \
		Path.o \
		PathManager.o \
		Point2.o \
		Point3.o \
		PointList3.o \
		PreferencesManager.o \
		QTScubaWidget.o \
		QtVolumeHistogram.o \
		ScubaColorLUT.o \
		ScubaDataCollectionFactory.o \
		ScubaFrame.o \
		ScubaGlobalPreferences.o \
		ScubaLayer2DMRI.o \
		ScubaLayer2DMRIS.o \
		ScubaLayerFactory.o \
		ScubaROI.o \
		ScubaROIVolume.o \
		ScubaToolState.o \
		ScubaTransform.o \
		ScubaView.o \
		ScubaWindowToRASTranslator.o \
		ShortestPathFinder.o \
		SurfaceCollection.o \
		TclCommandManager.o \
		TclProgressDisplayManager.o \
		test_VolumeHistogram.o \
		Timer.o \
		Transform44.o \
		UndoManager.o \
		Utilities.o \
		VectorOps.o \
		View.o \
		ViewState.o \
		Volume3.o \
		VolumeCollection.o \
		WindowFrame.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_QTScubaWidget.cpp \
		moc_QtVolumeHistogram.cpp
OBJMOC = moc_QTScubaWidget.o \
		moc_QtVolumeHistogram.o
DIST	   = testVolumeHistogram.pro
QMAKE_TARGET = testVolumeHistogram
DESTDIR  = 
TARGET   = testVolumeHistogram

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: test_VolumeHistogram.mak $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

test_VolumeHistogram.mak: testVolumeHistogram.pro  /usr/local/qt/mkspecs/default/qmake.conf /usr/local/qt/lib/libqt-mt.prl
	$(QMAKE) -o test_VolumeHistogram.mak testVolumeHistogram.pro
qmake: 
	@$(QMAKE) -o test_VolumeHistogram.mak testVolumeHistogram.pro

dist: 
	@mkdir -p .tmp/testVolumeHistogram && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/testVolumeHistogram/ && ( cd `dirname .tmp/testVolumeHistogram` && $(TAR) testVolumeHistogram.tar testVolumeHistogram && $(GZIP) testVolumeHistogram.tar ) && $(MOVE) `dirname .tmp/testVolumeHistogram`/testVolumeHistogram.tar.gz . && $(DEL_FILE) -r .tmp/testVolumeHistogram

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

Array2.o: Array2.cpp Array2.h \
		Point2.h

Broadcaster.o: Broadcaster.cpp Broadcaster.h \
		string_fixed.h \
		Listener.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h

DataCollection.o: DataCollection.cpp string_fixed.h \
		DataCollection.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		DebugReporter.h \
		IDTracker.h \
		TclCommandManager.h \
		ScubaROI.h \
		ScubaTransform.h \
		Transform44.h \
		Broadcaster.h \
		Point3.h \
		Matrix44.h \
		Listener.h

DataManager.o: DataManager.cpp string_fixed.h \
		DataManager.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		DebugReporter.h

DebugReporter.o: DebugReporter.cpp DebugReporter.h

IDTracker.o: IDTracker.cpp string_fixed.h \
		IDTracker.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h

InputState.o: InputState.cpp InputState.h \
		string_fixed.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h

Layer.o: Layer.cpp Layer.h \
		Utilities.h \
		Point2.h \
		string_fixed.h \
		ViewState.h \
		IDTracker.h \
		DebugReporter.h \
		TclCommandManager.h \
		ScubaWindowToRASTranslator.h \
		ScubaToolState.h \
		InputState.h \
		Listener.h \
		Broadcaster.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		Point3.h

Listener.o: Listener.cpp Listener.h \
		string_fixed.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h

Matrix44.o: Matrix44.cpp string_fixed.h \
		Matrix44.h \
		VectorOps.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		DebugReporter.h \
		Point3.h

Path.o: Path.cpp Path.h \
		VectorOps.h \
		Point3.h \
		IDTracker.h \
		Broadcaster.h \
		string_fixed.h \
		Listener.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h

PathManager.o: PathManager.cpp PathManager.h \
		string_fixed.h \
		Path.h \
		TclCommandManager.h \
		Listener.h \
		Broadcaster.h \
		UndoManager.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		Point3.h \
		IDTracker.h \
		DebugReporter.h

Point2.o: Point2.cpp Point2.h

Point3.o: Point3.cpp Point3.h

PointList3.o: PointList3.cpp PointList3.h \
		Point3.h

PreferencesManager.o: PreferencesManager.cpp string_fixed.h \
		PreferencesManager.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		DebugReporter.h

QTScubaWidget.o: QTScubaWidget.cpp string_fixed.h \
		QTScubaWidget.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		WindowFrame.h \
		DebugReporter.h \
		InputState.h \
		IDTracker.h

QtVolumeHistogram.o: QtVolumeHistogram.cpp string_fixed.h \
		QtVolumeHistogram.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		DebugReporter.h \
		VolumeCollection.h \
		DataCollection.h \
		ScubaROIVolume.h \
		Volume3.h \
		Point3.h \
		ScubaTransform.h \
		Broadcaster.h \
		IDTracker.h \
		TclCommandManager.h \
		ScubaROI.h \
		Transform44.h \
		Matrix44.h \
		Listener.h

ScubaColorLUT.o: ScubaColorLUT.cpp ScubaColorLUT.h \
		string_fixed.h \
		DebugReporter.h \
		TclCommandManager.h \
		IDTracker.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h

ScubaDataCollectionFactory.o: ScubaDataCollectionFactory.cpp ScubaDataCollectionFactory.h \
		VolumeCollection.h \
		SurfaceCollection.h \
		string_fixed.h \
		DebugReporter.h \
		TclCommandManager.h \
		DataCollection.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		IDTracker.h \
		ScubaROI.h \
		ScubaTransform.h \
		Transform44.h \
		Broadcaster.h \
		Point3.h \
		Matrix44.h \
		Listener.h \
		ScubaROIVolume.h \
		Volume3.h

ScubaFrame.o: ScubaFrame.cpp ScubaFrame.h \
		PreferencesManager.h \
		ScubaView.h \
		string_fixed.h \
		ToglManager.h \
		TclCommandManager.h \
		View.h \
		ScubaToolState.h \
		Listener.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		togl.h \
		WindowFrame.h \
		DebugReporter.h \
		InputState.h \
		IDTracker.h \
		Broadcaster.h \
		DataCollection.h \
		ViewState.h \
		Layer.h \
		ScubaWindowToRASTranslator.h \
		ScubaTransform.h \
		Point2.h \
		VolumeCollection.h \
		ScubaROI.h \
		Transform44.h \
		Point3.h \
		Matrix44.h \
		ScubaROIVolume.h \
		Volume3.h

ScubaGlobalPreferences.o: ScubaGlobalPreferences.cpp string_fixed.h \
		ScubaGlobalPreferences.h \
		PreferencesManager.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		TclCommandManager.h \
		Broadcaster.h \
		DebugReporter.h \
		Listener.h

ScubaLayer2DMRI.o: ScubaLayer2DMRI.cpp ScubaLayer2DMRI.h \
		ViewState.h \
		TclProgressDisplayManager.h \
		Utilities.h \
		Array2.h \
		PathManager.h \
		VectorOps.h \
		Layer.h \
		VolumeCollection.h \
		ScubaColorLUT.h \
		UndoManager.h \
		Timer.h \
		ShortestPathFinder.h \
		Path.h \
		Listener.h \
		string_fixed.h \
		IDTracker.h \
		DebugReporter.h \
		TclCommandManager.h \
		ScubaWindowToRASTranslator.h \
		ScubaToolState.h \
		InputState.h \
		Broadcaster.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		DataCollection.h \
		ScubaROIVolume.h \
		Volume3.h \
		Point3.h \
		ScubaTransform.h \
		ScubaROI.h \
		Transform44.h \
		Matrix44.h \
		Point2.h

ScubaLayer2DMRIS.o: ScubaLayer2DMRIS.cpp ScubaLayer2DMRIS.h \
		Layer.h \
		SurfaceCollection.h \
		string_fixed.h \
		ViewState.h \
		IDTracker.h \
		DebugReporter.h \
		TclCommandManager.h \
		ScubaWindowToRASTranslator.h \
		ScubaToolState.h \
		InputState.h \
		Listener.h \
		Broadcaster.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		DataCollection.h \
		ScubaROI.h \
		ScubaTransform.h \
		Transform44.h \
		Point3.h \
		Matrix44.h

ScubaLayerFactory.o: ScubaLayerFactory.cpp ScubaLayerFactory.h \
		ScubaLayer2DMRI.h \
		ScubaLayer2DMRIS.h \
		string_fixed.h \
		DebugReporter.h \
		TclCommandManager.h \
		Layer.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		ViewState.h \
		IDTracker.h \
		ScubaWindowToRASTranslator.h \
		ScubaToolState.h \
		InputState.h \
		Listener.h \
		Broadcaster.h \
		VolumeCollection.h \
		ScubaColorLUT.h \
		UndoManager.h \
		Timer.h \
		ShortestPathFinder.h \
		Path.h \
		DataCollection.h \
		ScubaROIVolume.h \
		Volume3.h \
		Point3.h \
		ScubaTransform.h \
		ScubaROI.h \
		Transform44.h \
		Matrix44.h \
		Point2.h \
		Array2.h \
		SurfaceCollection.h

ScubaROI.o: ScubaROI.cpp ScubaROI.h \
		ScubaColorLUT.h \
		string_fixed.h \
		DebugReporter.h \
		TclCommandManager.h \
		IDTracker.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h

ScubaROIVolume.o: ScubaROIVolume.cpp string_fixed.h \
		ScubaROIVolume.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		ScubaROI.h \
		DebugReporter.h \
		TclCommandManager.h \
		IDTracker.h

ScubaToolState.o: ScubaToolState.cpp string_fixed.h \
		ScubaToolState.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		IDTracker.h \
		TclCommandManager.h \
		DebugReporter.h

ScubaTransform.o: ScubaTransform.cpp ScubaTransform.h \
		VolumeCollection.h \
		string_fixed.h \
		Transform44.h \
		DebugReporter.h \
		TclCommandManager.h \
		IDTracker.h \
		Broadcaster.h \
		Point3.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		Matrix44.h \
		Listener.h \
		DataCollection.h \
		ScubaROIVolume.h \
		Volume3.h \
		ScubaROI.h

ScubaView.o: ScubaView.cpp string_fixed.h \
		ScubaView.h \
		PreferencesManager.h \
		ScubaGlobalPreferences.h \
		Timer.h \
		Point2.h \
		Point3.h \
		VectorOps.h \
		Utilities.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		View.h \
		DataCollection.h \
		InputState.h \
		ViewState.h \
		Layer.h \
		ScubaWindowToRASTranslator.h \
		ScubaToolState.h \
		ScubaTransform.h \
		VolumeCollection.h \
		IDTracker.h \
		DebugReporter.h \
		TclCommandManager.h \
		Listener.h \
		Broadcaster.h \
		ScubaROI.h \
		Transform44.h \
		Matrix44.h \
		ScubaROIVolume.h \
		Volume3.h

ScubaWindowToRASTranslator.o: ScubaWindowToRASTranslator.cpp ScubaWindowToRASTranslator.h

ShortestPathFinder.o: ShortestPathFinder.cpp ShortestPathFinder.h \
		Point2.h \
		Array2.h \
		DebugReporter.h

SurfaceCollection.o: SurfaceCollection.cpp string_fixed.h \
		SurfaceCollection.h \
		DataManager.h \
		VolumeCollection.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		DataCollection.h \
		DebugReporter.h \
		IDTracker.h \
		TclCommandManager.h \
		ScubaROI.h \
		ScubaTransform.h \
		Transform44.h \
		Broadcaster.h \
		Point3.h \
		Matrix44.h \
		Listener.h \
		ScubaROIVolume.h \
		Volume3.h

TclCommandManager.o: TclCommandManager.cpp string_fixed.h \
		TclCommandManager.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		DebugReporter.h

TclProgressDisplayManager.o: TclProgressDisplayManager.cpp string_fixed.h \
		TclProgressDisplayManager.h \
		TclCommandManager.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		DebugReporter.h

test_VolumeHistogram.o: test_VolumeHistogram.cpp Scuba-impl.h \
		QtVolumeHistogram.h \
		Volume3.cpp \
		Point2.cpp \
		Point3.cpp \
		Array2.cpp \
		Path.cpp \
		ShortestPathFinder.h \
		VolumeCollection.h \
		string_fixed.h \
		Volume3.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		Point2.h \
		Point3.h \
		Array2.h \
		Path.h \
		VectorOps.h \
		IDTracker.h \
		Broadcaster.h \
		Listener.h \
		DebugReporter.h \
		DataCollection.h \
		ScubaROIVolume.h \
		ScubaTransform.h \
		TclCommandManager.h \
		ScubaROI.h \
		Transform44.h \
		Matrix44.h

Timer.o: Timer.cpp Timer.h

Transform44.o: Transform44.cpp string_fixed.h \
		Transform44.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		Matrix44.h \
		Point3.h \
		DebugReporter.h

UndoManager.o: UndoManager.cpp UndoManager.h \
		string_fixed.h \
		TclCommandManager.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		DebugReporter.h

Utilities.o: Utilities.cpp string_fixed.h \
		Utilities.h \
		VectorOps.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		Point2.h \
		Point3.h

VectorOps.o: VectorOps.cpp VectorOps.h \
		Point3.h

View.o: View.cpp View.h \
		string_fixed.h \
		IDTracker.h \
		DebugReporter.h \
		InputState.h \
		TclCommandManager.h \
		ScubaToolState.h \
		Listener.h \
		Broadcaster.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h

ViewState.o: ViewState.cpp ViewState.h

Volume3.o: Volume3.cpp string_fixed.h \
		Volume3.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h

VolumeCollection.o: VolumeCollection.cpp string_fixed.h \
		VolumeCollection.h \
		DataManager.h \
		Point3.h \
		Utilities.h \
		PathManager.h \
		VectorOps.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		DataCollection.h \
		ScubaROIVolume.h \
		Volume3.h \
		ScubaTransform.h \
		Broadcaster.h \
		DebugReporter.h \
		IDTracker.h \
		TclCommandManager.h \
		ScubaROI.h \
		Transform44.h \
		Matrix44.h \
		Listener.h \
		Point2.h \
		Path.h \
		UndoManager.h

WindowFrame.o: WindowFrame.cpp string_fixed.h \
		WindowFrame.h \
		Point2.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		DebugReporter.h \
		InputState.h \
		IDTracker.h

moc_QTScubaWidget.o: moc_QTScubaWidget.cpp  QTScubaWidget.h string_fixed.h \
		WindowFrame.h \
		DebugReporter.h \
		InputState.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		IDTracker.h

moc_QtVolumeHistogram.o: moc_QtVolumeHistogram.cpp  QtVolumeHistogram.h string_fixed.h \
		DebugReporter.h \
		VolumeCollection.h \
		/usr/include/g++-3/alloc.h \
		/usr/include/g++-3/stl_config.h \
		/usr/include/g++-3/stl_alloc.h \
		/usr/include/g++-3/iostream.h \
		/usr/include/g++-3/streambuf.h \
		DataCollection.h \
		ScubaROIVolume.h \
		Volume3.h \
		Point3.h \
		ScubaTransform.h \
		Broadcaster.h \
		IDTracker.h \
		TclCommandManager.h \
		ScubaROI.h \
		Transform44.h \
		Matrix44.h \
		Listener.h

moc_QTScubaWidget.cpp: $(MOC) QTScubaWidget.h
	$(MOC) QTScubaWidget.h -o moc_QTScubaWidget.cpp

moc_QtVolumeHistogram.cpp: $(MOC) QtVolumeHistogram.h
	$(MOC) QtVolumeHistogram.h -o moc_QtVolumeHistogram.cpp

####### Install

install:  

uninstall:  

