#ifndef VolumeCollection_H
#define VolumeCollection_H

#include "string_fixed.h"
#include "DataCollection.h"
#include "ScubaROIVolume.h"
extern "C" {
#ifdef Status
#undef Status
#endif
#include "mri.h"
#ifdef X
  #undef X 
#endif
#ifdef Y
  #undef Y
#endif
#ifdef Z
  #undef Z
#endif
}
#include "Volume3.h"
#include "Point3.h"
#include "ScubaTransform.h"
#include "Broadcaster.h"

class VolumeCollection : public DataCollection {

  friend class VolumeCollectionTester;
  friend class VolumeCollectionFlooder;

 public:
  VolumeCollection ();
  virtual ~VolumeCollection ();

  // Should return a type description unique to the subclass.
  virtual std::string GetTypeDescription() { return "Volume"; }

  // Set the file name for this ROI. This will be used to load the MRI
  // and to save it.
  void SetFileName ( std::string& ifnMRI );

  // Creates an MRI using an existing data collection as a template.
  void MakeUsingTemplate ( int iCollectionID );

  // Get the MRI. If we're loading an MRI, this requires the MRI to be
  // set first.
  MRI* GetMRI ();

  // Saves the current volume to a file name. If none is given, uses
  // the set file name.
  void Save ();
  void Save ( std::string ifn );
  

  // Accessors.
  float GetMRIMinValue () { return mMRIMinValue; }
  float GetMRIMaxValue () { return mMRIMaxValue; }

  float GetMRIMagnitudeMinValue (); // (Calls MakeMagnitudeVolume if necessary)
  float GetMRIMagnitudeMaxValue ();

  float GetVoxelXSize () { return mVoxelSize[0]; }
  float GetVoxelYSize () { return mVoxelSize[1]; }
  float GetVoxelZSize () { return mVoxelSize[2]; }

  // Coordinate conversion.
  void RASToMRIIndex ( float iRAS[3], int oIndex[3] );
  void RASToMRIIndex ( float iRAS[3], float oIndex[3] );
  void MRIIndexToRAS ( int iIndex[3], float oRAS[3] );
  void MRIIndexToRAS ( float iIndex[3], float oRAS[3] );
  void RASToDataRAS  ( float iRAS[3], float oDataRAS[3] );

  // Bounds testing.
  bool IsRASInMRIBounds ( float iRAS[3] );
  bool IsMRIIndexInMRIBounds ( int iIndex[3] );

  // Calculates values.
  float GetMRINearestValueAtRAS ( float iRAS[3] );
  float GetMRITrilinearValueAtRAS ( float iRAS[3] );
  float GetMRISincValueAtRAS ( float iRAS[3] );
  float GetMRIMagnitudeValueAtRAS ( float iRAS[3] );
  
  // Sets value.
  void SetMRIValueAtRAS ( float iRAS[3], float iValue );
  
  virtual TclCommandResult
    DoListenToTclCommand ( char* isCommand, int iArgc, char** iasArgv );

  virtual void
    DoListenToMessage ( std::string isMessage, void* iData );

  // Create an ROI for this data collection.
  virtual ScubaROI* DoNewROI ();


  // For the selection cache. This is just for quick lookup to see if
  // any ROI is at this point.
  void SelectRAS ( float iRAS[3] );
  void UnselectRAS ( float iRAS[3] );

  // Return whether or not an ROI is at this point, and if so, returns
  // the color. If multiple ROIs are present, blends the color.
  bool IsRASSelected ( float iRAS[3], int oColor[3] );

  // Return whether or not an ROI is present other than the one passed
  // in.
  bool IsOtherRASSelected ( float iRAS[3], int iThisROIID );



  // Calculate and return a list of RAS points within a certain
  // area. Guaranteed to return one (or more!) RAS points for each
  // voxel in the area.
  void GetRASPointsInCube ( float iCenterRAS[3], float iRadius,
			    bool ibBrushX, bool ibBrushY, bool ibBrushZ,
			    std::list<Point3<float> >& oPoints );
  void GetRASPointsInSphere ( float iCenterRAS[3], float iRadius,
			      bool ibBrushX, bool ibBrushY, bool ibBrushZ,
			      std::list<Point3<float> >& oPoints );


  // Writes an ROI to a label file.
  void WriteROIToLabel ( int iROIID, std::string ifnLabel );

  // Creates a new ROI in this data collection from a label file.
  int  NewROIFromLabel ( std::string ifnLabel );

  // Writes all structure ROIs to a segmentation volume file.
  void WriteROIsToSegmentation ( std::string ifnVolume );


  // Sets the data to world transform, basically a user settable
  // display transform.
  virtual void SetDataToWorldTransform ( int iTransformID );


  // Returns the combined world to index transform.
  Matrix44& GetWorldToIndexTransform ();

  // Enable or disable world to index transform.
  void SetUseWorldToIndexTransform ( bool ibUse );


protected:

  // Gets information from the MRI structure.
  void InitializeFromMRI ();

  // Update the value range.
  void UpdateMRIValueRange ();

  // Calculates the final world to index transfrom from the data to
  // index transform and the world to index transform.
  void CalcWorldToIndexTransform ();

  // Calculates the magnitude volume and saves it in mMagnitudeMRI.
  void MakeMagnitudeVolume ();

  // Filename to use when reading or writing.
  std::string mfnMRI;

  // The actual MRI volume.
  MRI* mMRI;

  // The magnitude volume, used for the edge line tool. This is
  // generated by MakeMagnitudeVolume whenever a magnitude value is
  // set.
  MRI* mMagnitudeMRI;

  // We're dealing with two transforms here, data->world which is
  // defined in DataCollection, and data->index which is defined
  // here. Actually it goes world->data->index and
  // index->data->world. We composite these in the last transform.
  Transform44 mDataToIndexTransform;
  Transform44 mWorldToIndexTransform;

  bool mbUseDataToIndexTransform;

  // Voxel sizes.
  float mVoxelSize[3];

  // MRI and magnitude volume ranges.
  float mMRIMinValue, mMRIMaxValue;
  float mMRIMagMinValue, mMRIMagMaxValue;

  // The selected voxel cache.
  void InitSelectionVolume ();
  Volume3<bool>* mSelectedVoxels;
};

class VolumeCollectionFlooder {
 public:
  VolumeCollectionFlooder ();
  virtual ~VolumeCollectionFlooder ();

  // Override these to do startup and shutdown stuff, also allow the
  // user or program to cancel the flood.
  virtual void DoBegin ();  
  virtual void DoEnd ();
  virtual bool DoStopRequested ();

  virtual bool CompareVoxel ( float iRAS[3] );
  virtual void DoVoxel ( float iRAS[3] );

  class Params {
  public:
    Params ();
    int mSourceCollection;
    bool mbStopAtPaths;
    bool mbStopAtROIs;
    bool mb3D;
    bool mbWorkPlaneX;
    bool mbWorkPlaneY;
    bool mbWorkPlaneZ;
    float mViewNormal[3];
    int mFuzziness;
    int mMaxDistance;
    bool mbDiagonal;
  };

  class CheckPair {
  public:
    CheckPair() {}
    CheckPair( Point3<float>& iSource, Point3<float>& iCheck ) {
      mSourceRAS = iSource; mCheckRAS = iCheck;
    }
    Point3<float> mSourceRAS;
    Point3<float> mCheckRAS;
  };    

  void Flood ( VolumeCollection& iVolume, float iRASSeed[3], Params& iParams );
  VolumeCollection* mVolume;
  Params* mParams;
};


#endif
