# docker build for distributing a base fs 7.3.2 container

FROM quay.io/centos/centos:stream8

# shell settings
WORKDIR /root

# install utils
RUN yum -y update && \
    yum -y install bc libgomp perl tar tcsh wget vim-common && \
    yum -y install mesa-libGL libXext libSM libXrender libXmu && \
    yum clean all

# install fs
RUN wget --progress=bar:force:noscroll https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.3.2/freesurfer-linux-centos8_x86_64-7.3.2.tar.gz -O fs.tar.gz && \
    tar --no-same-owner -xzvf fs.tar.gz && \
    mv freesurfer /usr/local && \
    rm fs.tar.gz

# setup fs env
ENV PATH /usr/local/freesurfer/bin:/usr/local/freesurfer/fsfast/bin:/usr/local/freesurfer/tktools:/usr/local/freesurfer/mni/bin:${PATH} \
    OS Linux \
    FREESURFER_HOME /usr/local/freesurfer \
    FREESURFER /usr/local/freesurfer \
    SUBJECTS_DIR /usr/local/freesurfer/subjects \
    LOCAL_DIR /usr/local/freesurfer/local \
    FSFAST_HOME /usr/local/freesurfer/fsfast \
    FMRI_ANALYSIS_DIR /usr/local/freesurfer/fsfast \
    FUNCTIONALS_DIR /usr/local/freesurfer/sessions \
    FS_OVERRIDE 0 \
    FIX_VERTEX_AREA "" \
    FSF_OUTPUT_FORMAT nii.gz \
    MINC_BIN_DIR /usr/local/freesurfer/mni/bin \
    MINC_LIB_DIR /usr/local/freesurfer/mni/lib \
    MNI_DIR /usr/local/freesurfer/mni \
    MNI_DATAPATH /usr/local/freesurfer/mni/data \
    MNI_PERL5LIB /usr/local/freesurfer/mni/share/perl5 \
    PERL5LIB /usr/local/freesurfer/mni/share/perl5
