7.2.0:
	docker build -t freesurfer/freesurfer:7.2.0 -f ./Dockerfile.7.2.0 .

7.3.0:
	docker build -t freesurfer/freesurfer:7.3.0 -f ./Dockerfile.7.3.0 .

7.3.1:
	docker build -t freesurfer/freesurfer:7.3.1 -f ./Dockerfile.7.3.1 .

7.3.2:
	docker build -t freesurfer/freesurfer:7.3.2 -f ./Dockerfile.7.3.2 .
