#! /bin/tcsh -f

# run the talairach failure detector on a known good transforms
# and a known bad transform and check against expected results

set echo=1

./talairach_afd -xfm good_tal.xfm -afd ../distribution/fsafd -V > output
if ($status) exit 1

diff output good_tal.txt
if ($status) exit 1

./talairach_afd -xfm bad_tal.xfm -afd ../distribution/fsafd -V > output
# here, we expect it to have exited with failure:
if ($status == 0) exit 1

diff output bad_tal.txt
if ($status) exit 1

rm output

exit 0


