// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include "kvlImageThresholdingConsoleGUI.h"

void kvlImageThresholdingConsoleGUI::cb_m_Window_i(Fl_Double_Window*, void*) {
  exit( 0 );
}
void kvlImageThresholdingConsoleGUI::cb_m_Window(Fl_Double_Window* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->user_data()))->cb_m_Window_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_m_ImageViewer_i(kvl::ImageViewer*, void*) {
  //this->SelectTriangleContainingPoint( Fl::event_x(), m_ImageViewer->h() - Fl::event_y() );
}
void kvlImageThresholdingConsoleGUI::cb_m_ImageViewer(kvl::ImageViewer* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->user_data()))->cb_m_ImageViewer_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_m_OverlayOpacity_i(Fl_Value_Slider*, void*) {
  this->SetOverlayOpacity( m_OverlayOpacity->value() );
}
void kvlImageThresholdingConsoleGUI::cb_m_OverlayOpacity(Fl_Value_Slider* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->user_data()))->cb_m_OverlayOpacity_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_m_CoronalSliceNumber_i(Fl_Value_Slider*, void*) {
  this->SetSliceLocation( 
  static_cast< unsigned int >( m_SagittalSliceNumber->value() ),
  static_cast< unsigned int >( m_CoronalSliceNumber->value() ),
  static_cast< unsigned int >( m_AxialSliceNumber->value() ) );
}
void kvlImageThresholdingConsoleGUI::cb_m_CoronalSliceNumber(Fl_Value_Slider* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->user_data()))->cb_m_CoronalSliceNumber_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_m_SagittalSliceNumber_i(Fl_Value_Slider*, void*) {
  m_CoronalSliceNumber->do_callback();
}
void kvlImageThresholdingConsoleGUI::cb_m_SagittalSliceNumber(Fl_Value_Slider* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->user_data()))->cb_m_SagittalSliceNumber_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_m_AxialSliceNumber_i(Fl_Value_Slider*, void*) {
  m_CoronalSliceNumber->do_callback();
}
void kvlImageThresholdingConsoleGUI::cb_m_AxialSliceNumber(Fl_Value_Slider* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->user_data()))->cb_m_AxialSliceNumber_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_m_ViewOne_i(Fl_Round_Button*, void*) {
  this->ShowSelectedView();
}
void kvlImageThresholdingConsoleGUI::cb_m_ViewOne(Fl_Round_Button* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->parent()->user_data()))->cb_m_ViewOne_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_m_ViewTwo_i(Fl_Round_Button*, void*) {
  this->ShowSelectedView();
}
void kvlImageThresholdingConsoleGUI::cb_m_ViewTwo(Fl_Round_Button* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->parent()->user_data()))->cb_m_ViewTwo_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_m_ViewFour_i(Fl_Round_Button*, void*) {
  this->ShowSelectedView();
}
void kvlImageThresholdingConsoleGUI::cb_m_ViewFour(Fl_Round_Button* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->parent()->user_data()))->cb_m_ViewFour_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_m_ViewThree_i(Fl_Round_Button*, void*) {
  this->ShowSelectedView();
}
void kvlImageThresholdingConsoleGUI::cb_m_ViewThree(Fl_Round_Button* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->parent()->user_data()))->cb_m_ViewThree_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_m_ViewFive_i(Fl_Round_Button*, void*) {
  this->ShowSelectedView();
}
void kvlImageThresholdingConsoleGUI::cb_m_ViewFive(Fl_Round_Button* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->parent()->user_data()))->cb_m_ViewFive_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_m_ImageToThreshold_i(Fl_Browser* o, void*) {
  if ( o->value() )
  {
  this->SetImageToThreshold( o->value() - 1 );
  };
}
void kvlImageThresholdingConsoleGUI::cb_m_ImageToThreshold(Fl_Browser* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->user_data()))->cb_m_ImageToThreshold_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_m_ImageToMask_i(Fl_Browser* o, void*) {
  if ( o->value() )
  {
  this->SetImageToMask( o->value() - 1 );
  };
}
void kvlImageThresholdingConsoleGUI::cb_m_ImageToMask(Fl_Browser* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->user_data()))->cb_m_ImageToMask_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_m_LowerThreshold_i(Fl_Value_Slider*, void*) {
  if ( m_LowerThreshold->value() > m_UpperThreshold->value() )
{
  m_LowerThreshold->value( m_UpperThreshold->value() );
}


this->SetThresholds( m_LowerThreshold->value(), m_UpperThreshold->value() );
}
void kvlImageThresholdingConsoleGUI::cb_m_LowerThreshold(Fl_Value_Slider* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->user_data()))->cb_m_LowerThreshold_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_m_UpperThreshold_i(Fl_Value_Slider*, void*) {
  if ( m_UpperThreshold->value() < m_LowerThreshold->value() )
{
  m_UpperThreshold->value( m_LowerThreshold->value() );
}


this->SetThresholds( m_LowerThreshold->value(), m_UpperThreshold->value() );
}
void kvlImageThresholdingConsoleGUI::cb_m_UpperThreshold(Fl_Value_Slider* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->user_data()))->cb_m_UpperThreshold_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_Mask_i(Fl_Button*, void*) {
  this->MaskImage();
}
void kvlImageThresholdingConsoleGUI::cb_Mask(Fl_Button* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->user_data()))->cb_Mask_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_Show_i(Fl_Check_Button* o, void*) {
  if ( o->value() )
  {
  this->ShowInverseMask( true );
  }
else
  {
  this->ShowInverseMask( false );
  };
}
void kvlImageThresholdingConsoleGUI::cb_Show(Fl_Check_Button* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->user_data()))->cb_Show_i(o,v);
}

void kvlImageThresholdingConsoleGUI::cb_Write_i(Fl_Button*, void*) {
  this->WriteMask();
}
void kvlImageThresholdingConsoleGUI::cb_Write(Fl_Button* o, void* v) {
  ((kvlImageThresholdingConsoleGUI*)(o->parent()->user_data()))->cb_Write_i(o,v);
}

kvlImageThresholdingConsoleGUI::kvlImageThresholdingConsoleGUI() {
  { m_Window = new Fl_Double_Window(1280, 1030, "kvlImageThresholdingConsole");
    m_Window->callback((Fl_Callback*)cb_m_Window, (void*)(this));
    { m_ImageViewer = new kvl::ImageViewer(10, 10, 1000, 1000);
      m_ImageViewer->box(FL_FLAT_BOX);
      m_ImageViewer->color((Fl_Color)FL_FOREGROUND_COLOR);
      m_ImageViewer->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
      m_ImageViewer->labeltype(FL_NORMAL_LABEL);
      m_ImageViewer->labelfont(0);
      m_ImageViewer->labelsize(14);
      m_ImageViewer->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
      m_ImageViewer->callback((Fl_Callback*)cb_m_ImageViewer);
      m_ImageViewer->align(FL_ALIGN_TOP);
      m_ImageViewer->when(FL_WHEN_RELEASE);
      m_ImageViewer->end();
    } // kvl::ImageViewer* m_ImageViewer
    { m_OverlayOpacity = new Fl_Value_Slider(1070, 40, 175, 25, "Overlay opacity:");
      m_OverlayOpacity->type(1);
      m_OverlayOpacity->textsize(14);
      m_OverlayOpacity->callback((Fl_Callback*)cb_m_OverlayOpacity);
      m_OverlayOpacity->align(FL_ALIGN_TOP);
    } // Fl_Value_Slider* m_OverlayOpacity
    { m_CoronalSliceNumber = new Fl_Value_Slider(1070, 127, 175, 25, "Coronal slice number:");
      m_CoronalSliceNumber->type(1);
      m_CoronalSliceNumber->step(1);
      m_CoronalSliceNumber->textsize(14);
      m_CoronalSliceNumber->callback((Fl_Callback*)cb_m_CoronalSliceNumber);
      m_CoronalSliceNumber->align(FL_ALIGN_TOP);
    } // Fl_Value_Slider* m_CoronalSliceNumber
    { m_SagittalSliceNumber = new Fl_Value_Slider(1070, 222, 175, 25, "Sagittal slice number:");
      m_SagittalSliceNumber->type(1);
      m_SagittalSliceNumber->step(1);
      m_SagittalSliceNumber->textsize(14);
      m_SagittalSliceNumber->callback((Fl_Callback*)cb_m_SagittalSliceNumber);
      m_SagittalSliceNumber->align(FL_ALIGN_TOP);
    } // Fl_Value_Slider* m_SagittalSliceNumber
    { m_AxialSliceNumber = new Fl_Value_Slider(1070, 313, 175, 25, "Axial slice number:");
      m_AxialSliceNumber->type(1);
      m_AxialSliceNumber->step(1);
      m_AxialSliceNumber->textsize(14);
      m_AxialSliceNumber->callback((Fl_Callback*)cb_m_AxialSliceNumber);
      m_AxialSliceNumber->align(FL_ALIGN_TOP);
    } // Fl_Value_Slider* m_AxialSliceNumber
    { Fl_Group* o = new Fl_Group(1095, 376, 124, 109, "View");
      o->box(FL_DOWN_BOX);
      { m_ViewOne = new Fl_Round_Button(1105, 383, 29, 29);
        m_ViewOne->type(102);
        m_ViewOne->down_box(FL_ROUND_DOWN_BOX);
        m_ViewOne->callback((Fl_Callback*)cb_m_ViewOne);
        m_ViewOne->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
      } // Fl_Round_Button* m_ViewOne
      { m_ViewTwo = new Fl_Round_Button(1185, 382, 27, 28);
        m_ViewTwo->type(102);
        m_ViewTwo->down_box(FL_ROUND_DOWN_BOX);
        m_ViewTwo->callback((Fl_Callback*)cb_m_ViewTwo);
      } // Fl_Round_Button* m_ViewTwo
      { m_ViewFour = new Fl_Round_Button(1185, 448, 25, 29);
        m_ViewFour->type(102);
        m_ViewFour->down_box(FL_ROUND_DOWN_BOX);
        m_ViewFour->callback((Fl_Callback*)cb_m_ViewFour);
      } // Fl_Round_Button* m_ViewFour
      { m_ViewThree = new Fl_Round_Button(1105, 451, 24, 21);
        m_ViewThree->type(102);
        m_ViewThree->down_box(FL_ROUND_DOWN_BOX);
        m_ViewThree->callback((Fl_Callback*)cb_m_ViewThree);
      } // Fl_Round_Button* m_ViewThree
      { m_ViewFive = new Fl_Round_Button(1140, 415, 30, 27);
        m_ViewFive->type(102);
        m_ViewFive->down_box(FL_ROUND_DOWN_BOX);
        m_ViewFive->value(1);
        m_ViewFive->callback((Fl_Callback*)cb_m_ViewFive);
      } // Fl_Round_Button* m_ViewFive
      o->end();
    } // Fl_Group* o
    { m_ImageToThreshold = new Fl_Browser(1030, 525, 220, 135, "Image to threshold");
      m_ImageToThreshold->type(2);
      m_ImageToThreshold->callback((Fl_Callback*)cb_m_ImageToThreshold);
      m_ImageToThreshold->align(FL_ALIGN_TOP);
    } // Fl_Browser* m_ImageToThreshold
    { m_ImageToMask = new Fl_Browser(1030, 800, 220, 135, "Image to mask");
      m_ImageToMask->type(2);
      m_ImageToMask->callback((Fl_Callback*)cb_m_ImageToMask);
      m_ImageToMask->align(FL_ALIGN_TOP);
    } // Fl_Browser* m_ImageToMask
    { m_LowerThreshold = new Fl_Value_Slider(1050, 685, 175, 25, "Lower threshold::");
      m_LowerThreshold->type(1);
      m_LowerThreshold->step(1);
      m_LowerThreshold->textsize(14);
      m_LowerThreshold->callback((Fl_Callback*)cb_m_LowerThreshold);
      m_LowerThreshold->align(FL_ALIGN_TOP);
    } // Fl_Value_Slider* m_LowerThreshold
    { m_UpperThreshold = new Fl_Value_Slider(1050, 740, 175, 25, "Upper threshold:");
      m_UpperThreshold->type(1);
      m_UpperThreshold->step(1);
      m_UpperThreshold->textsize(14);
      m_UpperThreshold->callback((Fl_Callback*)cb_m_UpperThreshold);
      m_UpperThreshold->align(FL_ALIGN_TOP);
    } // Fl_Value_Slider* m_UpperThreshold
    { Fl_Button* o = new Fl_Button(1030, 940, 220, 30, "Mask image");
      o->callback((Fl_Callback*)cb_Mask);
    } // Fl_Button* o
    { Fl_Check_Button* o = new Fl_Check_Button(1205, 80, 40, 20, "Show inverse mask:");
      o->down_box(FL_DOWN_BOX);
      o->callback((Fl_Callback*)cb_Show);
      o->align(FL_ALIGN_LEFT);
    } // Fl_Check_Button* o
    { Fl_Button* o = new Fl_Button(1030, 975, 220, 30, "Write mask");
      o->callback((Fl_Callback*)cb_Write);
    } // Fl_Button* o
    m_Window->end();
    m_Window->resizable(m_Window);
  } // Fl_Double_Window* m_Window
}

kvlImageThresholdingConsoleGUI::~kvlImageThresholdingConsoleGUI() {
}

void kvlImageThresholdingConsoleGUI::SetOverlayOpacity( float overlayOpacity ) {
}

void kvlImageThresholdingConsoleGUI::SetSliceLocation( unsigned int, unsigned int, unsigned int ) {
}

void kvlImageThresholdingConsoleGUI::ShowSelectedView() {
}

void kvlImageThresholdingConsoleGUI::SetImageToThreshold( int ) {
}

void kvlImageThresholdingConsoleGUI::SetImageToMask( int ) {
}

void kvlImageThresholdingConsoleGUI::SetThresholds( float, float ) {
}

void kvlImageThresholdingConsoleGUI::MaskImage() {
}

void kvlImageThresholdingConsoleGUI::ShowInverseMask( bool ) {
}

void kvlImageThresholdingConsoleGUI::WriteMask() {
}
