#ifndef ERRORCODE_H
#define ERRORCODE_H

enum ERROR_CODE 
{	
	TE_NO_ERROR = 0,

	// Track IO error
	TE_CAN_NOT_OPEN,
	TE_CAN_NOT_CLOSE,
	TE_CAN_NOT_READ,
	TE_CAN_NOT_WRITE,
	TE_NOT_TRACK_FILE,
	TE_NOT_INITIALIZED,
	
	CAN_NOT_OPEN = TE_CAN_NOT_OPEN,
	CAN_NOT_READ = TE_CAN_NOT_READ,
	CAN_NOT_WRITE = TE_CAN_NOT_WRITE,
	CAN_NOT_READ_BODY = CAN_NOT_READ,
	CAN_NOT_READ_HEADER,
	NOT_SUPPORTED_FORMAT,	
	CAN_NOT_ALLOCATE,
	USER_ABORTED,
	FILE_ALREADY_OPENED,
	
	UNKNOWN_ERROR
};


#endif

