#!/usr/bin/env bash
[ ! -e "$FREESURFER_FSPYTHON" ] && echo "error: freesurfer has not been properly sourced" && exit 1

if [[ ! -v RUN_FSDEEPNET ]]; then
    echo "Running Freesurfer version of @SCRIPTNAME@ ..."
    echo "$FREESURFER_FSPYTHON/bin/fspython $FREESURFER_FSPYTHON/python/scripts/@SCRIPTNAME@ $@"
    echo
    exec $FREESURFER_FSPYTHON/bin/fspython $FREESURFER_FSPYTHON/python/scripts/@SCRIPTNAME@ "$@"
else
    echo "Running FSdeepnet version of @SCRIPTNAME@ ..."
    echo "$FREESURFER_FSPYTHON/bin/fspython $FREESURFER_FSPYTHON/python/lib/python$FSPYTHON_VERSION/site-packages/fsdeepnet/apps/@SCRIPTNAME@/cli/@SCRIPTNAME@.py $@"
    echo
    exec $FREESURFER_FSPYTHON/bin/fspython $FREESURFER_FSPYTHON/python/lib/python$FSPYTHON_VERSION/site-packages/fsdeepnet/apps/@SCRIPTNAME@/cli/@SCRIPTNAME@.py "$@"
fi
