#!/usr/bin/env python
# -*- coding: latin-1 -*-

import sys
import os
import platform
import textwrap
import shlex
import subprocess
from distutils.spawn import find_executable


# =========================================================================== #
#                                     VARS                                    #
# =========================================================================== #

# terminal and output width:
TERMW = OUTW = int(os.popen("stty size", 'r').read().split()[1])
if TERMW > 80: OUTW = 80  # output max width

# output:
VERBOSE = True

HELPTEXT = None   # will be set programmatically
TAB = '    '      # 4-space standard tab
NOCOLORS = False  # if true, turn off colored output
COLDICT = {
  'k' : '\033[30m',  # black
  'r' : '\033[31m',  # red
  'g' : '\033[32m',  # green
  'y' : '\033[33m',  # yellow
  'b' : '\033[34m',  # blue
  'm' : '\033[35m',  # magenta
  'c' : '\033[36m',  # cyan
  'w' : '\033[37m',  # white
  '*' : '\033[1m' ,  # bold
  'e' : '\033[0m' }  # end (return to normal)

# for testing purposes:
SIMULATE = False 


# =========================================================================== #
#                                    CLASSES                                  #
# =========================================================================== #


# ================== VOL ============================== #
# an instance of this class represents a volume
# specified by the user, along with its appropriate
# loading options
# ===================================================== #
class Vol:
  def __init__(self, parent):
    self.isSubjVol = False
    self.type = 'volume'
    self.file = None
    self.path = None
    self.params = parent
    self.suboptions = []
    self.optdict = {}
    self.infomsg = {}

  # ---------------- Vol.getPath ---------------------- #
  # sets up valid path to file
  def getPath(self):
    # preliminary check: if file is not found in working dir, but found
    # in subject directory, use the subject volume
    if not os.path.isfile(self.file) and self.params.subj_name \
    and os.path.isfile(self.params.subj_path + "/mri/" + self.file):
      self.isSubjVol = True
    # create file path for volume: 
    if self.isSubjVol:  # if subject vol, precede path with subject dir
      if self.params.subj_name:
        self.path = os.path.join(self.params.subj_path, "mri", self.file)
      else:
        msg = "cannot load subject volume " + col(self.file, 'g') + \
              " because no subject was specified"
        errorExit(msg)
    else:
      self.path = self.file
    # does path exist:
    checkFile(self.path)

  # ---------------- Vol.writeCMD --------------------- #
  # checks if file is valid, prints volume info to the
  # terminal, and returns the associated freeview cmd argument
  def writeCMD(self):
    # set up file path:
    self.getPath()
    # create freeview command line argument for volume:
    cmdarg = " " + self.path
    # parse suboptions:
    for option in self.suboptions:
      fvsubopt = option.split("=")
      if len(fvsubopt) == 2:
        self.optdict[fvsubopt[0]] = fvsubopt[1]
        # colormap
        if fvsubopt[0] == "colormap":
          self.infomsg["cmap"] = "using " + col(fvsubopt[1], 'g') + " colormap"
        # registration
        if fvsubopt[0] == "reg":
          checkFile(fvsubopt[1])
          self.infomsg["reg"] = "registered with " + col(fvsubopt[1], 'g')
    # write suboptions:
    for key in self.optdict:
      cmdarg += ":" + key + "=" + self.optdict[key]
    # print volume info message for user:
    info = col(self.file, 'b')
    for key in self.infomsg:
      info += " - " + self.infomsg[key]
    self.params.printParam(self.type+'s', info)
    return cmdarg


# ================== SURF ============================= #
# an instance of this class represents a surface
# specified by the user, along with its appropriate
# loading options
# ===================================================== #
class Surf:
  def __init__(self, parent):
    self.isSubjSurf = False
    self.file = None
    self.path = None
    self.params = parent
    self.suboptions = []
    self.optdict = {}
    self.infomsg = {}

  # ---------------- Surf.getPath --------------------- #
  # sets up path to file
  def getPath(self):
    # preliminary check: if file is not found in working dir, but found
    # in subject directory, use the subject surf
    if not os.path.isfile(self.file) and self.params.subj_name \
    and os.path.isfile(self.params.subj_path + "/surf/" + self.file):
      self.isSubjSurf = True
    # create file path for surface:
    if self.isSubjSurf:  # if subject surf, precede path with subject dir
      if self.params.subj_name:
        self.path = os.path.join(self.params.subj_path, "surf", self.file)
      else:
        msg = "cannot load subject surface " + col(self.file, 'g') + \
              " because no subject was specified"
        errorExit(msg)
    else:
      self.path = self.file
    # does path exist:
    checkFile(self.path)

  # ---------------- Surf.writeCMD --------------------- #
  # checks if file is valid, prints surface info to the
  # terminal, and returns the associated freeview cmd argument
  def writeCMD(self):
    # set up file path:
    self.getPath()
    # create freeview command line argument for surface:
    cmdarg = " " + self.path
    # parse suboptions:
    for option in self.suboptions:
      fvsubopt = option.split("=")
      if len(fvsubopt) == 2:
        self.optdict[fvsubopt[0]] = fvsubopt[1]
    # write suboptions:
    for key in self.optdict:
      cmdarg += ":" + key + "=" + self.optdict[key]
    # print volume info message for user:
    info = col(self.file, 'b')
    for key in self.infomsg:
      info += " - " + self.infomsg[key]
    self.params.printParam("surfs", info)
    return cmdarg


# ================== PARAMS =========================== #
# parameter handler containing everything necessary to
# construct the freeview command: volumes, surfaces,
# subject info, view settings
# ===================================================== #
class Params:
  def __init__(self):
    self.subjs_dir = os.environ.get("SUBJECTS_DIR")
    self.subj_name = None
    self.subj_path = None
    self.nvols = 0
    self.nsurfs = 0
    self.vol_list = []
    self.surf_list = []
    self.fvoptions = ""
    self.last_param = None

  # ---------------- Params.vols ---------------------- #
  # returns a list of volumes of the given type. useful
  # for loading by order of type (eg. segs, overlays)
  def vols(self, voltype):
    return [v for v in self.vol_list if v.type == voltype]

  # ---------------- Params.surfs --------------------- #
  # returns a list of all surfaces. not very necessary,
  # but good for consistency (see Params.vols above)
  def surfs(self):
    return self.surf_list

  # ---------------- Params.setSubject ---------------- #
  # sets the subj_path and subj_name if the given subject is valid
  def setSubject(self, sname):
    if not self.subjs_dir:
      errorExit("SUBJECTS_DIR is not set")
    elif not os.path.isdir(self.subjs_dir):
      errorExit("SUBJECTS_DIR " + col(self.subjs_dir, "g") + " does not exist")
    self.subj_name = sname
    self.subj_path = os.path.join(self.subjs_dir, self.subj_name)
    if not os.path.isdir(self.subj_path):
      msg = "subject " + col(self.subj_name, "g")
      msg += " does not exist in SUBJECTS_DIR " + self.subjs_dir
      errorExit(msg)

  # ---------------- Params.addVol -------------------- #
  # creates a volume instance and adds it to vol_list.
  # parses the provided arguments and returns when an
  # unrecognized option is reached
  def addVol(self, argv, SUBJVOL=False, TYPE="volume"):
    vol = Vol(self)
    if len(argv) < 1:
      errorExit("must provide volume file path after option flag")
    vol.file = argv[0]  # set volume filename
    # set volume attributes:
    vol.isSubjVol = SUBJVOL
    vol.type = TYPE
    # set default type options:
    dopt = []
    if TYPE == "seg":
      dopt = ["colormap=lut", "opacity=0.2"]
    elif TYPE == 'overlay':
      dopt = ["colormap=heat", "opacity=0.8"]
    # put default opts at front of list so they don't overwrite anything:
    vol.suboptions = dopt + argv[1:]
    self.vol_list.append(vol)
    self.nvols += 1
    return len(argv)

  # ---------------- Params.addSurf ------------------- #
  # creates a surface instance and adds it to surf_list.
  # parses the provided arguments and returns when an
  # unrecognized option is reached
  def addSurf(self, argv, SUBJSURF=False):
    surf = Surf(self)
    if len(argv) < 1:
      errorExit("must provide surface file path after option flag")
    surf.file = argv[0]  # set surface filename
    # set surface attributes:
    surf.isSubjSurf = SUBJSURF
    # set default type options:
    dopt = []
    if surf.file.endswith("white"): dopt = ["edgecolor=white"]
    elif surf.file.endswith("pial"): dopt = ["edgecolor=pink"]
    # put default opts at front of list so they don't overwrite anything:
    surf.suboptions = dopt + argv[1:]
    # add created surface to loading list:
    self.surf_list.append(surf)
    self.nsurfs += 1
    return len(argv)

  # ---------------- Params.printParam ---------------- #
  # prints info for a parameter to summarize what is
  # being loaded. for visual purposes, this function keeps
  # track of the last parameter type printed so that it
  # doesn't print the type name multiple times in a row
  def printParam(self, paramtype, info):
    if not VERBOSE: return
    string = ""
    if self.last_param != paramtype: string = paramtype + ": "
    print "%*s" % (10, string) + info
    self.last_param = paramtype


# =========================================================================== #
#                                     UTILS                                   #
# =========================================================================== #


# ------------------ errorExit ------------------------ #
def errorExit(msg):
  print col("error:", "r*"), msg + '\n'
  sys.exit(1)


# ------------------ isOption -------------------------- #
# returns true if input string begins with -
def isOption(option): return option[0] == "-"


# ------------------ checkFile ------------------------- #
# exits with error if file doesn't exist
def checkFile(fname):
  if not os.path.isfile(fname):
    msg = "file " + col(fname, 'g') + " does not exist"
    errorExit(msg)
  return


# ------------------ stripKey -------------------------- #
# removes a given pattern from the beginning of a string.
# used to parse any additional options provided for
# vols and surfs
def stripKey(key, pattern): return key[len(pattern):]


# ------------------ col ------------------------------ #
# prints a string with a given style. see colorDict
def col(strng, color):
  # check if output is a tty:
  tty = hasattr(sys.stdout, 'isatty') and sys.stdout.isatty()
  # check if tty allows colors:
  pform = platform.system() in ("Darwin", "Linux")
  colors_enabled = tty and pform
  if not colors_enabled or NOCOLORS:
    return strng
  else:
    colstring = ""
    for i in range(len(color)):
      colstring += COLDICT[color[i]]
    colstring += strng + COLDICT['e']
    return colstring


# ------------------ compileHelp ---------------------- #
# organizes the provided sections of the help output
# and writes the text to the global HELPTEXT variable,
# which should be directly printed when appropriate
def compileHelp(progname, subtitle, usage, info, optns):
  global HELPTEXT
  # write title and subtitle:
  HELPTEXT = '\n' + col("NAME",'*') + '\n' + TAB + col(title, '*')
  HELPTEXT += " - " + subtitle + '\n\n'
  # write usage:
  HELPTEXT += col("USAGE", '*') + '\n' 
  # for multi-line usage text:
  for uline in usage.split('\n'): HELPTEXT += TAB + uline + '\n'
  HELPTEXT += '\n'
  # write usage info:
  if info:
    HELPTEXT += textwrap.fill(info, OUTW-2, initial_indent=(TAB), \
                              subsequent_indent=(TAB)) + "\n\n"
  # write options:
  HELPTEXT += col("OPTIONS", '*') + '\n' + optns
  return


# ------------------ addOpt --------------------------- #
# returns an option description for the help text.
def addOpt(flags, desc, subopt=None):
  # write the flag(s):
  option = TAB  # initial indent for opt flags
  for i, f in enumerate(flags):
    if i > 0:
      option += ", "
    option += col(f, '*')
  # write suboption arg requirement(s):
  if subopt: option += "  " + col(subopt, 'b')
  # write description:
  for par in desc.split('\n\n'):  # textwrap ignores newlines
    option += '\n' + textwrap.fill(par, OUTW-2, initial_indent=(TAB*2), \
                                   subsequent_indent=(TAB*2))
  return option + '\n\n'


# ------------------ getSubOptions -------------------- #
# extracts suboptions following an option flag
def getSubOptions(args):
  # init suboption array and begin parse:
  suboptions = []
  for arg in args[1:]:
    if isOption(arg): break
    else: suboptions.append(arg)
  return suboptions


# ------------------ parseCommandLine ------------------ #
# parses command line args and returns a Params object
def parseCommandLine(argv):
  params = Params()
  idx = 0
  while idx < len(argv):
    key = argv[idx]

    # ARGUMENT: the only argument provided should be the subject name
    if not isOption(key) and not params.subj_name:
      params.setSubject(key)

    # OPTION: load volume
    elif key in ('-v', '--vol'):
      subopts = getSubOptions(argv[idx:])
      idx += params.addVol(subopts)

    # OPTION: load subject volume
    elif key in ('-sv', '--subjvol'):
      subopts = getSubOptions(argv[idx:])
      idx += params.addVol(subopts, SUBJVOL=True)

    # OPTION: load segmentation volume
    elif key in ('-seg', '--segment'):
      subopts = getSubOptions(argv[idx:])
      idx += params.addVol(subopts, TYPE='seg')

    # OPTION: load overlay volume
    elif key in ('-ov', '--overlay'):
      subopts = getSubOptions(argv[idx:])
      idx += params.addVol(subopts, TYPE='ov')

    # OPTION: load surface
    elif key in ('-f', '--surf'):
      idx += params.addSurf(argv[idx:])

    # OPTION: load lh and rh, white and pial
    elif key in ('-surfs', '--surfs'):
      params.addSurf(['lh.pial'], SUBJSURF=True)
      params.addSurf(['lh.white'], SUBJSURF=True)
      params.addSurf(['rh.pial'], SUBJSURF=True)
      params.addSurf(['rh.white'], SUBJSURF=True)

    # OPTION: load standard recon files
    elif key in ('-r', '--recon'):
      params.addVol(['norm.mgz'], SUBJVOL=True)
      params.addVol(['T1.mgz'], SUBJVOL=True)
      params.addVol(['brainmask.mgz'], SUBJVOL=True)
      params.addVol(['wm.mgz', 'visible=false', 'opacity=0.2',
                     'colormap=heat'], SUBJVOL=True)
      params.addVol(['aparc+aseg.mgz'], SUBJVOL=True, TYPE='seg')
      params.addSurf(['lh.pial'], SUBJSURF=True)
      params.addSurf(['lh.white'], SUBJSURF=True)
      params.addSurf(['rh.pial'], SUBJSURF=True)
      params.addSurf(['rh.white'], SUBJSURF=True)

    # OPTION: load subject orig
    elif key in ('-orig', '--orig'):
      params.addVol(['orig.mgz'], SUBJVOL=True)

    # OPTION: load subject T1
    elif key in ('-T1', '--T1'):
      params.addVol(['T1.mgz'], SUBJVOL=True)

    # OPTION: load subject wm
    elif key in ('-wm', '--whitematter'):
      params.addVol(['wm.mgz', 'opacity=0.4','colormap=heat'], SUBJVOL=True)

    # OPTION: load subject aparc+aseg
    elif key in ('-apas', '--aparc+aseg'):
      params.addVol(['aparc+aseg.mgz'], SUBJVOL=True, TYPE='seg')

    # OPTION: set cursor CRS
    elif key in ('-crs', '--crs'):
      crs = getSubOptions(argv[idx:])
      if len(crs) < 3: errorExit("must provide col, row, and slice for -crs")
      params.fvoptions += " -slice" + crs[0] + " " + crs[1] + " " + crs[2]
      idx += 3

    # OPTION: quiet mode
    elif key in ('-q', '--quiet'):
      global VERBOSE
      VERBOSE = False

    # OPTION: show help
    elif key in ('-h', '-help', '--help'):
      print HELPTEXT
      sys.exit(0)

    # OPTION: simulate for testing purposes
    elif key in ('--sim'):
      global SIMULATE
      SIMULATE = True

    # UNKNOWN ARGUMENT:
    else:
      msg = "unknown argument " + col(key, 'g') + ". use -h for help"
      errorExit(msg)

    idx += 1
  return params


# =========================================================================== #
#                                     HELP                                    #
# =========================================================================== #


title    = "easyfv"
subtitle = "a freeview wrapper for quick and simple loading"
usage    = col("easyfv", '*') + " [options]" + '\n' + \
           col("easyfv", '*') + " subject [options]"
info     = """Files must be loaded using the option flags. easyfv will also
accept a subject name as an initial argument (SUBJECTS_DIR must be set), and
if a specified file is not found from the working directory, easyfv will search
for it in the subject's directory."""
opts     = ""

# OPTION: load volume
desc = """Load a volume file. Any sub-options available in freeview can
be specified as additional arguments.\n
example: easyfv -v mri.mgz opacity=0.5 colormap=heat"""
opts += addOpt(["-v", "--vol"], desc, subopt="<vol> <opts>...")

# OPTION: load subject volume
desc = """Load a subject-specific volume. This volume file must be located
in the subject's mri directory. Volume sub-options can also be used"""
opts += addOpt(["-sv", "--subjvol"], desc, subopt="<vol> <opts>...")

# OPTION: load segmentation volume
desc = """Load a volume file as a segmentation. This applies a set of
predefined settings to the volume, but these sub-options can be overwritten
with additional arguments (see -v)"""
opts += addOpt(["-seg", "--segment"], desc, subopt="<vol> <opts>...")

# OPTION: load overlay volume
desc = """Load a volume file as an overlay. This applies a heat colormap to
the volume. More options can be applied with additional
arguments (see -v)"""
opts += addOpt(["-ov", "--overlay"], desc, subopt="<vol> <opts>...")

# OPTION: load surface
desc = """Load a surface file. Surface sub-options can be specified
with the following additional arguments:"""
opts += addOpt(["-f", "--surf"], desc, subopt="<surf> <opts>...")

# OPTION: load lh and rh, white and pial
desc = "Load lh and rh, white and pial surfaces"
opts += addOpt(["-surfs", "--surfs"], desc)

# OPTION: load standard recon files
desc = "Load a series of predefined subject volumes and surfaces"
opts += addOpt(["-r", "--recon"], desc)

# OPTION: load subject orig
desc = "Load the subject's orig.mgz (subject must be set)"
opts += addOpt(["-orig", "--orig"], desc)

# OPTION: load subject T1
desc = "Load the subject's T1.mgz (subject must be set)"
opts += addOpt(["-T1", "--T1"], desc)

# OPTION: load subject wm
desc = "Load the subject's wm.mgz as a heatmap (subject must be set)"
opts += addOpt(["-wm", "--whitematter"], desc)

# OPTION: load subject aseg+aparc
desc = "Load the subject's aseg+aparc.mgz segmentation (subject must be set)"
opts += addOpt(["-asap", "--aseg+aparc"], desc)

# OPTION: position cursor CRS
desc = "Position the cursor at the given column, row, slice"
opts += addOpt(["-crs", "--crs"], desc, subopt="<col> <row> <slice>")

# OPTION: quiet mode
opts += addOpt(["-q", "--quiet"], "Quiet mode - suppress output")

# OPTION: show help
opts += addOpt(["-h", "-help", "--help"], "Display this help text")


compileHelp(title, subtitle, usage, info, opts)


# =========================================================================== #
#                                     MAIN                                    #
# =========================================================================== #


def main(argv):

  # init and parse arguments:
  params = parseCommandLine(argv)

  # check if freeview is on the path:
  if not find_executable('freeview'):
    msg = "cannot find freeview command. Make sure FREESURFER_HOME has " + \
          "been sourced:\nsource $FREESURFER_HOME/SetUpFreeSurfer.sh"
    errorExit(msg)

  # check if nothing will be loaded:
  if params.nvols == params.nsurfs == 0:
    if params.subj_name:
      # if nothing but subject name is provided, load orig.mgz:
      print "no volumes specified - loading orig.mgz as default"
      params.addVol(["orig.mgz"], SUBJVOL=True)
    else:
      print HELPTEXT
      exit(1)

  # init freeview command:
  fvcommand = "freeview"

  # print subject name if given:
  if params.subj_name:
    params.printParam("subject", col(params.subj_name, 'b'))

  # load volumes:
  if params.nvols > 0:
    fvcommand += " -v"
    for v in params.vols("volume"):  # load regular volumes first
      fvcommand += v.writeCMD()
    for v in params.vols("seg"):  # load seg volumes next
     fvcommand += v.writeCMD()
    for v in params.vols("overlay"):  # load overlay volumes last
     fvcommand += v.writeCMD()

  # load surfaces:
  if params.nsurfs > 0:
    fvcommand += " -f"
    for s in params.surfs():
      fvcommand += s.writeCMD()

  # append additional freeview options:
  fvcommand += params.fvoptions

  # print the freeview command:
  if VERBOSE:
    print "\nfreeview command:"
    print col('-' * TERMW, 'b')  # print blue line
    print fvcommand
    print col('-' * TERMW, 'b') + '\n'  # print blue line

  # run fv command:
  fvargs = shlex.split(fvcommand)
  if SIMULATE:
    retcode = 0
  else:
    retcode = subprocess.call(fvargs)

  return retcode




if __name__ == "__main__":
  retcode = main(sys.argv[1:])
  sys.exit(retcode)