#! /bin/tcsh -f

#
# fix_subject_corrected-lh
#
#
#
# Copyright © 2021 The General Hospital Corporation (Boston, MA) "MGH"
#
# Terms and conditions for use, reproduction, distribution and contribution
# are found in the 'FreeSurfer Software License Agreement' contained
# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
#
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
#
# Reporting: freesurfer@nmr.mgh.harvard.edu
#
#


setenv DIAG 0x04048
pushd $SUBJECTS_DIR/$1/scripts
pushd $SUBJECTS_DIR/$1
touch NOTES
echo " " >> NOTES
echo $0 $* >> NOTES
whoami >> NOTES
hostname >> NOTES
date >> NOTES
popd

mris_sphere -inflate -w 0 -q ../surf/lh.inflated ../surf/lh.qsphere
mris_fix_topology -suffix _corrected $1 lh
mris_smooth ../surf/lh.orig_corrected ../surf/lh.smoothwm_corrected
mris_inflate ../surf/lh.smoothwm_corrected ../surf/lh.inflated_corrected
mris_curvature -w -a 10 ../subjects/lh.smoothwm
cp ../surf/lh.smoothwm.H ../surf/lh.curv
mris_curvature -w -a 10 ../subjects/lh.smoothwm_corrected
cp ../surf/lh.smoothwm_corrected.H ../surf/lh.curv_corrected
mris_make_surfaces -w 0 -suffix _corrected  $1 lh
popd





















































































