#! /bin/tcsh -ef

#
# fix_subject-lh
#
# REPLACE_WITH_ONE_LINE_SHORT_DESCRIPTION
#
# Original Author: REPLACE_WITH_FULL_NAME_OF_CREATING_AUTHOR
# CVS Revision Info:
#    $Author: nicks $
#    $Date: 2011/03/02 20:16:39 $
#    $Revision: 1.3 $
#
# Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
#
# Terms and conditions for use, reproduction, distribution and contribution
# are found in the 'FreeSurfer Software License Agreement' contained
# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
#
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
#
# Reporting: freesurfer@nmr.mgh.harvard.edu
#
#

cd $SUBJECTS_DIR/$1/scripts

#mri_tessellate ../mri/filled 255 ../surf/lh.orig
#mris_smooth ../surf/lh.orig ../surf/lh.smoothwm
#mris_inflate -dist 0 ../surf/lh.smoothwm ../surf/lh.inflated
#mris_sphere -w 0  -q ../surf/lh.inflated ../surf/lh.qsphere

mris_sphere -w 0 -inflate -in 200  -q ../surf/lh.inflated ../surf/lh.qsphere
mris_fix_topology $1 lh
mris_smooth  ../surf/lh.orig ../surf/lh.smoothwm
mris_inflate ../surf/lh.smoothwm ../surf/lh.inflated
