#! /bin/tcsh -ef

#
# fix_subject-lh
#
# REPLACE_WITH_ONE_LINE_SHORT_DESCRIPTION
#
# Original Author: REPLACE_WITH_FULL_NAME_OF_CREATING_AUTHOR
# CVS Revision Info:
#    $Author: nicks $
#    $Date: 2007/01/06 00:01:14 $
#    $Revision: 1.2 $
#
# Copyright (C) 2002-2007,
# The General Hospital Corporation (Boston, MA).
# All rights reserved.
#
# Distribution, usage and copying of this software is covered under the
# terms found in the License Agreement file named 'COPYING' found in the
# FreeSurfer source code root directory, and duplicated here:
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferOpenSourceLicense
#
# General inquiries: freesurfer@nmr.mgh.harvard.edu
# Bug reports: analysis-bugs@nmr.mgh.harvard.edu
#

cd $SUBJECTS_DIR/$1/scripts

#mri_tessellate ../mri/filled 255 ../surf/lh.orig
#mris_smooth ../surf/lh.orig ../surf/lh.smoothwm
#mris_inflate -dist 0 ../surf/lh.smoothwm ../surf/lh.inflated
#mris_sphere -w 0  -q ../surf/lh.inflated ../surf/lh.qsphere

mris_sphere -w 0 -inflate -in 200  -q ../surf/lh.inflated ../surf/lh.qsphere
mris_fix_topology $1 lh
mris_smooth  ../surf/lh.orig ../surf/lh.smoothwm
mris_inflate ../surf/lh.smoothwm ../surf/lh.inflated
