#! /bin/tcsh -f

#
# fix_subject_corrected-lh
#
# REPLACE_WITH_ONE_LINE_SHORT_DESCRIPTION
#
# Original Author: REPLACE_WITH_FULL_NAME_OF_CREATING_AUTHOR
# CVS Revision Info:
#    $Author: nicks $
#    $Date: 2007/01/06 00:01:14 $
#    $Revision: 1.2 $
#
# Copyright (C) 2002-2007,
# The General Hospital Corporation (Boston, MA).
# All rights reserved.
#
# Distribution, usage and copying of this software is covered under the
# terms found in the License Agreement file named 'COPYING' found in the
# FreeSurfer source code root directory, and duplicated here:
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferOpenSourceLicense
#
# General inquiries: freesurfer@nmr.mgh.harvard.edu
# Bug reports: analysis-bugs@nmr.mgh.harvard.edu
#


setenv DIAG 0x04048
pushd $SUBJECTS_DIR/$1/scripts
pushd $SUBJECTS_DIR/$1
touch NOTES
echo " " >> NOTES
echo $0 $* >> NOTES
whoami >> NOTES
hostname >> NOTES
date >> NOTES
popd

mris_sphere -inflate -w 0 -q ../surf/lh.inflated ../surf/lh.qsphere
mris_fix_topology -suffix _corrected $1 lh
mris_smooth ../surf/lh.orig_corrected ../surf/lh.smoothwm_corrected
mris_inflate ../surf/lh.smoothwm_corrected ../surf/lh.inflated_corrected
mris_curvature -w -a 10 ../subjects/lh.smoothwm
cp ../surf/lh.smoothwm.H ../surf/lh.curv
mris_curvature -w -a 10 ../subjects/lh.smoothwm_corrected
cp ../surf/lh.smoothwm_corrected.H ../surf/lh.curv_corrected
mris_make_surfaces -w 0 -suffix _corrected  $1 lh
popd





















































































