#! /bin/tcsh

#
# inflate_subject_new-lh
#
#
#
# Copyright © 2021 The General Hospital Corporation (Boston, MA) "MGH"
#
# Terms and conditions for use, reproduction, distribution and contribution
# are found in the 'FreeSurfer Software License Agreement' contained
# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
#
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
#
# Reporting: freesurfer@nmr.mgh.harvard.edu
#
#

pushd $SUBJECTS_DIR/$1/
touch NOTES
echo " " >> NOTES
echo $0 $* >> NOTES
whoami >> NOTES
date >> NOTES
hostname >> NOTES
popd

pushd $SUBJECTS_DIR/$1/scripts
mri_tessellate ../mri/filled 255 ../surf/lh.orig_$2
mris_smooth ../surf/lh.orig_$2 ../surf/lh.smoothwm_$2
mris_inflate ../surf/lh.smoothwm_$2 ../surf/lh.inflated_$2
popd
