#! /bin/tcsh

#
# inflate_subject_new-lh
#
# REPLACE_WITH_ONE_LINE_SHORT_DESCRIPTION
#
# Original Author: REPLACE_WITH_FULL_NAME_OF_CREATING_AUTHOR
# CVS Revision Info:
#    $Author: nicks $
#    $Date: 2007/01/06 00:01:14 $
#    $Revision: 1.2 $
#
# Copyright (C) 2002-2007,
# The General Hospital Corporation (Boston, MA).
# All rights reserved.
#
# Distribution, usage and copying of this software is covered under the
# terms found in the License Agreement file named 'COPYING' found in the
# FreeSurfer source code root directory, and duplicated here:
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferOpenSourceLicense
#
# General inquiries: freesurfer@nmr.mgh.harvard.edu
# Bug reports: analysis-bugs@nmr.mgh.harvard.edu
#

pushd $SUBJECTS_DIR/$1/
touch NOTES
echo " " >> NOTES
echo $0 $* >> NOTES
whoami >> NOTES
date >> NOTES
hostname >> NOTES
popd

pushd $SUBJECTS_DIR/$1/scripts
mri_tessellate ../mri/filled 255 ../surf/lh.orig_$2
mris_smooth ../surf/lh.orig_$2 ../surf/lh.smoothwm_$2
mris_inflate ../surf/lh.smoothwm_$2 ../surf/lh.inflated_$2
popd
