#! /bin/tcsh -ef

#
# inflate_subject_sc
#
# REPLACE_WITH_ONE_LINE_SHORT_DESCRIPTION
#
# Original Author: REPLACE_WITH_FULL_NAME_OF_CREATING_AUTHOR
# CVS Revision Info:
#    $Author: nicks $
#    $Date: 2007/01/06 00:01:14 $
#    $Revision: 1.2 $
#
# Copyright (C) 2002-2007,
# The General Hospital Corporation (Boston, MA).
# All rights reserved.
#
# Distribution, usage and copying of this software is covered under the
# terms found in the License Agreement file named 'COPYING' found in the
# FreeSurfer source code root directory, and duplicated here:
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferOpenSourceLicense
#
# General inquiries: freesurfer@nmr.mgh.harvard.edu
# Bug reports: analysis-bugs@nmr.mgh.harvard.edu
#



setenv DIAG 0x04040

# -P allows the specification of a point in the brainstem at which
# to cut horizontally. This must be a slice in which the brainstem
# is not connected to cortex or cerebellum, etc...

# mri_fill -P 0.4 -25.9 -17.2  ../mri/wm ../mri/filled
cd  $SUBJECTS_DIR/$1/scripts
mri_fill -segmentation ../mri/aseg ../mri/wm ../mri/filled
inflate_subject-lh $1
inflate_subject-rh $1

