#! /bin/tcsh -ef

#
# inflate_subject-rh
#
#
#
# Copyright © 2021 The General Hospital Corporation (Boston, MA) "MGH"
#
# Terms and conditions for use, reproduction, distribution and contribution
# are found in the 'FreeSurfer Software License Agreement' contained
# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
#
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
#
# Reporting: freesurfer@nmr.mgh.harvard.edu
#
#


pushd $SUBJECTS_DIR/$1/
touch NOTES
echo " " >> NOTES
echo $0 $* >> NOTES
whoami >> NOTES
date >> NOTES
hostname >> NOTES
popd

cd $SUBJECTS_DIR/$1/scripts
mri_tessellate ../mri/filled 127 ../surf/rh.orig
mris_smooth ../surf/rh.orig ../surf/rh.smoothwm
mris_inflate -dist 0 ../surf/rh.smoothwm ../surf/rh.inflated
