#! /bin/tcsh -ef

#
# label_child
#
# REPLACE_WITH_ONE_LINE_SHORT_DESCRIPTION
#
# Original Author: REPLACE_WITH_FULL_NAME_OF_CREATING_AUTHOR
# CVS Revision Info:
#    $Author: nicks $
#    $Date: 2007/01/06 00:01:14 $
#    $Revision: 1.3 $
#
# Copyright (C) 2002-2007,
# The General Hospital Corporation (Boston, MA).
# All rights reserved.
#
# Distribution, usage and copying of this software is covered under the
# terms found in the License Agreement file named 'COPYING' found in the
# FreeSurfer source code root directory, and duplicated here:
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferOpenSourceLicense
#
# General inquiries: freesurfer@nmr.mgh.harvard.edu
# Bug reports: analysis-bugs@nmr.mgh.harvard.edu
#


setenv LTA   talairach.lta
setenv ASEG  aseg
setenv GCA $FREESURFER_HOME/average/talairach_children_b.gca
setenv GCA $FREESURFER_HOME/average/talairach_children_tl_b.gca

setenv s $1

set sdir = $SUBJECTS_DIR/$s/mri
mkdir -p $sdir/$ASEG
mri_ca_label -tl $GCA_TL -mask $sdir/brain  $sdir/norm $sdir/transforms/$LTA $GCA $sdir/$ASEG
