#! /bin/tcsh -ef

#
# label_subject_flash
#
#
#
# Copyright © 2021 The General Hospital Corporation (Boston, MA) "MGH"
#
# Terms and conditions for use, reproduction, distribution and contribution
# are found in the 'FreeSurfer Software License Agreement' contained
# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
#
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
#
# Reporting: freesurfer@nmr.mgh.harvard.edu
#
#


setenv LTA   talairach.lta
setenv ASEG  aseg
setenv GCA $FREESURFER_HOME/average/n7.gca

setenv s $1

set sdir = $SUBJECTS_DIR/$s/mri
mkdir -p $sdir/$ASEG
mri_ca_label  -flash $FREESURFER_HOME/average/tissue_parms.txt  $sdir/norm $sdir/transforms/$LTA $GCA $sdir/$ASEG
