#! /bin/tcsh -ef

#
# label_child
#
# REPLACE_WITH_ONE_LINE_SHORT_DESCRIPTION
#
# Original Author: REPLACE_WITH_FULL_NAME_OF_CREATING_AUTHOR
# CVS Revision Info:
#    $Author: nicks $
#    $Date: 2011/03/02 20:16:39 $
#    $Revision: 1.4 $
#
# Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
#
# Terms and conditions for use, reproduction, distribution and contribution
# are found in the 'FreeSurfer Software License Agreement' contained
# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
#
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
#
# Reporting: freesurfer@nmr.mgh.harvard.edu
#
#


setenv LTA   talairach.lta
setenv ASEG  aseg
setenv GCA $FREESURFER_HOME/average/talairach_children_b.gca
setenv GCA $FREESURFER_HOME/average/talairach_children_tl_b.gca

setenv s $1

set sdir = $SUBJECTS_DIR/$s/mri
mkdir -p $sdir/$ASEG
mri_ca_label -tl $GCA_TL -mask $sdir/brain  $sdir/norm $sdir/transforms/$LTA $GCA $sdir/$ASEG
