#!/bin/tcsh -ef

setenv LTA   talairach.lta
setenv ASEG  aseg
setenv GCA $FREESURFER_HOME/average/talairach_children_b.gca
setenv GCA $FREESURFER_HOME/average/talairach_children_tl_b.gca

setenv s $1

set sdir = $SUBJECTS_DIR/$s/mri
mkdir -p $sdir/$ASEG
mri_ca_label -tl $GCA_TL -mask $sdir/brain  $sdir/norm $sdir/transforms/$LTA $GCA $sdir/$ASEG
