#!/bin/tcsh -ef

setenv LTA   talairach.lta
setenv ASEG  aseg
setenv GCA $FREESURFER_HOME/average/n7.gca
setenv GCA $FREESURFER_HOME/average/mixed.gca

setenv s $1

set sdir = $SUBJECTS_DIR/$s/mri
mkdir -p $sdir/$ASEG
mri_ca_label  $sdir/norm $sdir/transforms/$LTA $GCA $sdir/$ASEG
