#! /bin/tcsh -ef

#
# map_central_sulcus
#
# $1 = subject name
# $2 = hemisphere
#
# Original Author: REPLACE_WITH_FULL_NAME_OF_CREATING_AUTHOR
# CVS Revision Info:
#    $Author: nicks $
#    $Date: 2007/01/06 00:01:14 $
#    $Revision: 1.2 $
#
# Copyright (C) 2002-2007,
# The General Hospital Corporation (Boston, MA).
# All rights reserved.
#
# Distribution, usage and copying of this software is covered under the
# terms found in the License Agreement file named 'COPYING' found in the
# FreeSurfer source code root directory, and duplicated here:
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferOpenSourceLicense
#
# General inquiries: freesurfer@nmr.mgh.harvard.edu
# Bug reports: analysis-bugs@nmr.mgh.harvard.edu
#


#mris_spherical_average -o $1 label $2-central_sulc $2 \
#  sphere.reg margaret $SUBJECTS_DIR/$1/label/$2-central_sulc_margaret.label

recon-all -s $1 -hemi $2 -avglabels


exit $status



