#! /bin/tcsh -ef

#
# map_central_sulcus
#
# $1 = subject name
# $2 = hemisphere
#
# Original Author: REPLACE_WITH_FULL_NAME_OF_CREATING_AUTHOR
# CVS Revision Info:
#    $Author: nicks $
#    $Date: 2011/03/02 20:16:39 $
#    $Revision: 1.3 $
#
# Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
#
# Terms and conditions for use, reproduction, distribution and contribution
# are found in the 'FreeSurfer Software License Agreement' contained
# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
#
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
#
# Reporting: freesurfer@nmr.mgh.harvard.edu
#
#


#mris_spherical_average -o $1 label $2-central_sulc $2 \
#  sphere.reg margaret $SUBJECTS_DIR/$1/label/$2-central_sulc_margaret.label

recon-all -s $1 -hemi $2 -avglabels


exit $status



