#!/bin/tcsh -f

#
# morph_only_subject-lh
#
# CVS Revision Info:
#    $Author: nicks $
#    $Date: 2007/01/06 00:01:14 $
#    $Revision: 1.3 $
#
# Copyright (C) 2002-2007,
# The General Hospital Corporation (Boston, MA).
# All rights reserved.
#
# Distribution, usage and copying of this software is covered under the
# terms found in the License Agreement file named 'COPYING' found in the
# FreeSurfer source code root directory, and duplicated here:
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferOpenSourceLicense
#
# General inquiries: freesurfer@nmr.mgh.harvard.edu
# Bug reports: analysis-bugs@nmr.mgh.harvard.edu
#

pushd $SUBJECTS_DIR/$1/
touch NOTES
echo " " >> NOTES
echo $0 $* >> NOTES
whoami >> NOTES
date >> NOTES
hostname >> NOTES
popd


pushd $SUBJECTS_DIR/$1/scripts
#mris_sphere -w 0 ../surf/lh.inflated ../surf/lh.sphere
mris_register -w 0 -curv ../surf/lh.sphere $FREESURFER_HOME/average/lh.average.tif ../surf/lh.sphere.reg
mris_register -w 0 ../surf/lh.sphere $FREESURFER_HOME/average/lh.average.tif ../surf/lh.sphere.dist_new
popd
