#!/bin/tcsh
pushd $SUBJECTS_DIR/$1/
touch NOTES
echo " " >> NOTES
echo $0 $* >> NOTES
whoami >> NOTES
date >> NOTES
hostname >> NOTES
popd


set hemi = rh

pushd $SUBJECTS_DIR/$1/scripts
#if (-e $SUBJECTS_DIR/$1/surf/$hemi.sphere == 0)  \
#		mris_sphere -w 0 ../surf/$hemi.inflated ../surf/$hemi.sphere ; \
#endif

mris_sphere -w 0 ../surf/$hemi.inflated ../surf/$hemi.sphere 
mris_register -w 0 -curv \
		../surf/$hemi.sphere \
		$MRI_DIR/average/$hemi.average.tif \
		../surf/$hemi.sphere.reg
set SVIT_DIR    = $SUBJECTS_DIR/$1/svit
if (-e $SVIT_DIR == 0) \
    mkdir $SVIT_DIR ;\
endif

set SLF = $SVIT_DIR/$hemi.sphere.reg.svit.log
mri-structvits -subject $1 -umask 0 \
		-hemi $hemi -outdir $SVIT_DIR -can sphere.reg | tee -a $SLF
morph_rgb-$hemi $1


#mris_register -w 0 ../surf/$hemi.sphere $MRI_DIR/average/$hemi.average.tif ../surf/$hemi.sphere.dist_new
popd
