#!/bin/tcsh -f

#
# morph_tables-rh
#
#
#
# Copyright © 2021 The General Hospital Corporation (Boston, MA) "MGH"
#
# Terms and conditions for use, reproduction, distribution and contribution
# are found in the 'FreeSurfer Software License Agreement' contained
# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
#
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
#
# Reporting: freesurfer@nmr.mgh.harvard.edu
#
#

pushd $SUBJECTS_DIR/$1/
touch NOTES
echo " " >> NOTES
echo $0 $* >> NOTES
whoami >> NOTES
date >> NOTES
hostname >> NOTES
popd


set hemi = rh

pushd $SUBJECTS_DIR/$1/scripts
set SVIT_DIR    = $SUBJECTS_DIR/$1/svit
if (-e $SVIT_DIR == 0) \
    mkdir $SVIT_DIR ;\
endif

set SLF = $SVIT_DIR/$hemi.sphere.reg.svit.log
mri-structvits -subject $1 -umask 0 \
		-hemi $hemi -outdir $SVIT_DIR -can sphere.reg | tee -a $SLF

popd
