#!/bin/tcsh -f

#
# morph_only_subject-lh
#
#
# Copyright © 2021 The General Hospital Corporation (Boston, MA) "MGH"
#
# Terms and conditions for use, reproduction, distribution and contribution
# are found in the 'FreeSurfer Software License Agreement' contained
# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
#
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
#
# Reporting: freesurfer@nmr.mgh.harvard.edu
#
#

pushd $SUBJECTS_DIR/$1/
touch NOTES
echo " " >> NOTES
echo $0 $* >> NOTES
whoami >> NOTES
date >> NOTES
hostname >> NOTES
popd


pushd $SUBJECTS_DIR/$1/scripts
#mris_sphere -w 0 ../surf/lh.inflated ../surf/lh.sphere
mris_register -w 0 -curv ../surf/lh.sphere $FREESURFER_HOME/average/lh.average.tif ../surf/lh.sphere.reg
mris_register -w 0 ../surf/lh.sphere $FREESURFER_HOME/average/lh.average.tif ../surf/lh.sphere.dist_new
popd
