#!/usr/bin/env python2


import os
import sys
import argparse
import glob
from subprocess import call


def errExit(message):
  print('error: ' + message)
  exit(1)


# ---- parse args ----

parser = argparse.ArgumentParser(description="prepares a given freesurfer glm dir for 'palm' processing")
parser._action_groups.pop()  #  list required arguments before optional
required = parser.add_argument_group('required arguments')
optional = parser.add_argument_group('optional arguments')
required.add_argument('--glmdir', metavar='PATH', type=str, help='the glm directory to prepare', required=True)
required.add_argument('--zthresh', metavar='FLOAT', type=str, help='z-threshold', required=True)
required.add_argument('--iterations', metavar='INT', type=int, help='number of iterations', required=True)
optional.add_argument('--palmdir', metavar='NAME', type=str, help='name of palm subdirectory (default="palm")', default="palm")
# check for no args first
if len(sys.argv) == 1:
  parser.print_help()
  sys.exit(1)
args = parser.parse_args()

# check glmdir
glmdir = os.path.abspath(args.glmdir)
if not os.path.isdir(glmdir):
  errExit('"{0}" is not a valid directory'.format(glmdir))
# make palm subdir
palmdir = os.path.join(glmdir, args.palmdir)
print('preparing a palm subdirectory in {0}'.format(palmdir))
# os.makedirs(palmdir, exist_ok=True)  # python3
if not os.path.exists(palmdir): os.makedirs(palmdir)  # settle for python2 for now


# ---- glm info ----

glm_log = os.path.join(glmdir, 'mri_glmfit.log')
if not os.path.isfile(glm_log):
  errExit('cannot find mri_glmfit.log in the glm directory')
with open(glm_log, "r") as f:
  loglines = [line for line in f.readlines() if line.strip()]

# extract hemi
hemi = ''
for line in loglines:
  splitline = line.split()
  if splitline[0] == 'cmdline':
    if 'lh' in splitline: hemi = 'lh'
    elif 'rh' in splitline: hemi = 'rh'
    break
if not hemi:
  errExit("could not extract hemi info from mri_glmfit.log")

# extract input filename
input_file = ''
for line in loglines:
  if line.split()[0] == 'y':
    input_file = line.split()[1]
    break
if not input_file:
  errExit("could not extract input filename from mri_glmfit.log")
if not os.path.isfile(input_file):
  errExit('mri_glmfit input file "{0}" is no longer available at this location'.format(input_file))
print('using the original glmfit input file {0}'.format(input_file))


# ---- design matrix ----

# read the Xg.dat
xg_path = os.path.join(glmdir, 'Xg.dat')
if not os.path.isfile(xg_path):
  errExit('cannot find Xg.dat in the glm directory')
with open(xg_path) as f:
  xg_content = f.readlines()
xg_content = [x.strip() for x in xg_content]
num_points = len(xg_content)
num_waves = len(xg_content[0].split())

# write the palm design.mat
f = open(os.path.join(palmdir, 'design.mat'), "w")
f.write('/NumWaves {0}\n'.format(num_waves))
f.write('/NumPoints {0}\n'.format(num_points))
f.write('/Matrix\n')
for thing in xg_content:
  if len(thing.split()) != num_waves:
    errExit('number of waves (cols) in Xg.dat are not consistent')
  f.write(thing + '\n')
f.close()


# ---- contrasts ----

# read in the C.dat files
contrast_paths = glob.glob('{0}/*/C.dat'.format(glmdir))
if len(contrast_paths) == 0:
  errExit('cannot find any contrast subdirs (with C.dat) in the glm directory')
contrasts = []
for constrast_file in contrast_paths:
  with open(xg_path) as f:
    contrasts.append(f.readline().strip())

# write the palm design.con
f = open(os.path.join(palmdir, 'design.con'), "w")
f.write('/NumWaves {0}\n'.format(num_waves))
f.write('/NumPoints {0}\n'.format(len(contrasts)))
f.write('/Matrix\n')
for contrast in contrasts:
  if len(contrast.split()) != num_waves:
    errExit('number of waves (cols) are not consistent')
  f.write(contrast + '\n')
f.close()


# ---- mask ----

maskfile = ''
for fileformat in ['.mgz', '.mgh', '.nii', '.nii.gz']:
  if os.path.isfile(os.path.join(glmdir, 'mask' + fileformat)):
    maskfile = os.path.join(glmdir, 'mask' + fileformat)
    break
if not maskfile:
  errExit('cannot find any mask volume in the glm directory')
if maskfile.endswith('.nii.gz'):
  # nii.gz mask can't be used - must convert to nii
  maskfile = maskfile[:-3]
  print('"nii.gz" format is unsupported - converting mask.nii.gz to mask.nii')
  call(['mri_convert', maskfile + '.gz', maskfile])
print('using mask volume {0}'.format(maskfile))

# ---- matlab script ----

script_content = """\
input = '{0}'; 

hemi = '{1}'; 

maskfile = '{2}'; 

zthresh = {3}
niterations = {4}

FREESURFER_HOME = getenv('FREESURFER_HOME'); 
surffile = sprintf('%s/subjects/fsaverage/surf/%s.white', FREESURFER_HOME, hemi);
zthreshstr = sprintf('%f', zthresh); 
niterationsstr = sprintf('%d', niterations); 

palm('-i', input, '-rmethod', 'Freedman-Lane', '-m', maskfile, ... 
     '-s', surffile, '-d', 'design.mat', '-t', 'design.con', ... 
     '-T', '-C', zthreshstr, '-n', niterationsstr, '-o', 'palm');
""".format(input_file, hemi, maskfile, args.zthresh, args.iterations)

# write the run_palm.m script
script_path = os.path.join(palmdir, 'run_palm.m')
with open(script_path, "w") as f:
  f.write(script_content)
print('palmprep complete - matlab script created at {0}'.format(script_path))
