#!/bin/tcsh -ef

setenv hemi lh
set subject=$1
mris_ca_label -t $CSURF_DIR/Simple_surface_labels2002.txt $subject $hemi sphere.reg $CSURF_DIR/average/${hemi}.atlas2002_simple.gcs $SUBJECTS_DIR/$subject/label/${hemi}.aparc.annot
#mris_ca_label $1 $hemi sphere.reg $MRI_DIR/average/${hemi}_trans_toSulc.gcs ${hemi}_aparc.annot

