#!/bin/tcsh -ef

setenv GCA $FREESURFER_HOME/average/mixed.gca
setenv LTA talairach.lta

setenv s $1

set sdir = $SUBJECTS_DIR/$s/mri
foreach d (fsamples norm transforms)
	mkdir -p $sdir/$d ;\
end


~fischl/build/mri_em_register/mri_em_register -flash $FREESURFER_HOME/average/tissue_parms.txt -fsamples $sdir/fsamples -norm $sdir/norm $sdir/orig $GCA $sdir/transforms/$LTA

