#! /bin/tcsh -ef

#
# remove_talairach
#
# REPLACE_WITH_ONE_LINE_SHORT_DESCRIPTION
#
# Original Author: REPLACE_WITH_FULL_NAME_OF_CREATING_AUTHOR
# CVS Revision Info:
#    $Author: nicks $
#    $Date: 2007/01/06 00:01:15 $
#    $Revision: 1.2 $
#
# Copyright (C) 2002-2007,
# The General Hospital Corporation (Boston, MA).
# All rights reserved.
#
# Distribution, usage and copying of this software is covered under the
# terms found in the License Agreement file named 'COPYING' found in the
# FreeSurfer source code root directory, and duplicated here:
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferOpenSourceLicense
#
# General inquiries: freesurfer@nmr.mgh.harvard.edu
# Bug reports: analysis-bugs@nmr.mgh.harvard.edu
#


cd $SUBJECTS_DIR/$1/mri
foreach d (orig T1 brain wm seg seg_edited cma_seg filled aseg fsamples temporal_lobe norm tmp)
		if (-e $d/COR-.info == 1) then
			  echo removing xform line from directory $d
				rm -f $d/COR-.info.bak
				mv -f $d/COR-.info $d/COR-.info.bak
				grep -v ^xform $d/COR-.info.bak >$d/COR-.info
		endif
end

