#! /bin/tcsh -ef

#
# remove_talairach
#
#
#
# Copyright © 2021 The General Hospital Corporation (Boston, MA) "MGH"
#
# Terms and conditions for use, reproduction, distribution and contribution
# are found in the 'FreeSurfer Software License Agreement' contained
# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
#
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
#
# Reporting: freesurfer@nmr.mgh.harvard.edu
#
#


cd $SUBJECTS_DIR/$1/mri
foreach d (orig T1 brain wm seg seg_edited cma_seg filled aseg fsamples temporal_lobe norm tmp)
		if (-e $d/COR-.info == 1) then
			  echo removing xform line from directory $d
				rm -f $d/COR-.info.bak
				mv -f $d/COR-.info $d/COR-.info.bak
				grep -v ^xform $d/COR-.info.bak >$d/COR-.info
		endif
end

