#!/bin/tcsh -ef

setenv GCA $FREESURFER_HOME/average/mixed.gca
setenv LTA talairach.lta

setenv s $1

set sdir = $SUBJECTS_DIR/$s/mri
foreach d (fsamples norm transforms)
	mkdir -p $sdir/$d ;\
end


mri_em_register -fsamples $sdir/fsamples -norm $sdir/norm $sdir/norm $GCA $sdir/transforms/$LTA

