#! /bin/tcsh -ef

#
# test_mri_segstats
#
# execute and check eTIV results against expected results
#
# Original Author: Nick Schmansky
# CVS Revision Info:
#    $Author: nicks $
#    $Date: 2009/11/23 15:29:58 $
#    $Revision: 1.1 $
#
# Copyright (C) 2009
# The General Hospital Corporation (Boston, MA). 
# All rights reserved.
#
# Distribution, usage and copying of this software is covered under the
# terms found in the License Agreement file named 'COPYING' found in the
# FreeSurfer source code root directory, and duplicated here:
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferOpenSourceLicense
#
# General inquiries: freesurfer@nmr.mgh.harvard.edu
# Bug reports: analysis-bugs@nmr.mgh.harvard.edu
#

set VERSION='$Id: test_mri_segstats,v 1.1 2009/11/23 15:29:58 nicks Exp $'

umask 002

#
# extract testing data
#
gunzip -c testdata.tar.gz | tar xvf -

#
# run command
#
set cmd=(./mri_segstats --subject testdata --etiv-only)
echo ""
echo $cmd
$cmd > testout.txt
if ($status != 0) then
  echo "mri_segstats FAILED"
  exit 1
endif

#
# look for differences
#
set cmd=(diff testout.txt testexpected.txt)
echo ""
echo $cmd
$cmd
set diff_status=$status
if ($diff_status != 0) then
  echo "$cmd FAILED (exit status=$diff_status)"
  exit 1
endif

