# TCLTKTIXBLT Find Module

if(NOT TCLTKTIXBLT_DIR)
  set(TCLTKTIXBLT_DIR ${FS_PACKAGES_DIR}/tcltktixblt/8.4.6)
endif()

find_path(TCLTKTIXBLT_INCLUDE_DIR HINTS ${TCLTKTIXBLT_DIR} NAMES tcl.h PATH_SUFFIXES include NO_DEFAULT_PATH)

find_library(TCL_LIBRARY HINTS ${TCLTKTIXBLT_DIR} PATH_SUFFIXES lib NO_DEFAULT_PATH NAMES tcl8.4)
find_library(TK_LIBRARY  HINTS ${TCLTKTIXBLT_DIR} PATH_SUFFIXES lib NO_DEFAULT_PATH NAMES tk8.4)
find_library(BLT_LIBRARY HINTS ${TCLTKTIXBLT_DIR} PATH_SUFFIXES lib NO_DEFAULT_PATH NAMES BLT)
find_library(TIX_LIBRARY HINTS ${TCLTKTIXBLT_DIR} PATH_SUFFIXES lib NO_DEFAULT_PATH NAMES tix8.1.8.4)

find_package_handle_standard_args(TCLTKTIXBLT DEFAULT_MSG TCLTKTIXBLT_INCLUDE_DIR TCL_LIBRARY TK_LIBRARY TIX_LIBRARY BLT_LIBRARY)

set(TCLTKTIXBLT_LIBRARIES ${BLT_LIBRARY} ${TIX_LIBRARY} ${TK_LIBRARY} ${TCL_LIBRARY})

# make sure the shared libs get installed on linux
if(TCLTKTIXBLT_FOUND AND NOT APPLE)
  file(GLOB TCL_LIBRARIES_TO_INSTALL "${TCLTKTIXBLT_DIR}/lib/lib*.so*")
  install(PROGRAMS ${TCL_LIBRARIES_TO_INSTALL} DESTINATION lib)
endif()
