#! /bin/tcsh -ef

#
# test_mri_concatenate_lta
#
# execute and check results against expected results
#
# Original Author: Nick Schmansky
# CVS Revision Info:
#    $Author: nicks $
#    $Date: 2011/05/02 21:19:33 $
#    $Revision: 1.6 $
#
# Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
#
# Terms and conditions for use, reproduction, distribution and contribution
# are found in the 'FreeSurfer Software License Agreement' contained
# in the file 'LICENSE' found in the FreeSurfer distribution, and here:
#
# https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense
#
# Reporting: freesurfer@nmr.mgh.harvard.edu
#

set VERSION='$Id: test_mri_concatenate_lta,v 1.6 2011/05/02 21:19:33 nicks Exp $'

umask 002

#
# extract testing data
#
gunzip -c testdata.tar.gz | tar xvf -

#
# run command1
#
set cmd=(./mri_concatenate_lta -invert1 \
  nick13_to_nickbase.lta \
  identity.nofile \
  nickbase_to_nick13.lta)
echo ""
echo $cmd
$cmd
if ($status != 0) then
  echo "mri_concatenate_lta test1 FAILED"
  exit 1
endif

#
# look for differences
#
set cmd=(diff nickbase_to_nick13.lta reference-nickbase_to_nick13.lta)
if ("`uname -p`" == "powerpc") then
  set cmd=(diff nickbase_to_nick13.lta reference-ppc-nickbase_to_nick13.lta)
endif
echo ""
echo $cmd
$cmd
set diff_status=$status
if ($diff_status != 0) then
  echo "$cmd FAILED (exit status=$diff_status)"
  exit 1
endif

#
# run command2
#
set cmd=(./mri_concatenate_lta 002.lta \
  tp_to_base.lta \
  002-long.lta)
echo ""
echo $cmd
$cmd
if ($status != 0) then
  echo "mri_concatenate_lta test2 FAILED"
  exit 1
endif

#
# look for differences
#
set cmd=(diff 002-long.lta reference-002-long.lta)
if ("`uname -p`" == "powerpc") then
  set cmd=(diff 002-long.lta reference-ppc-002-long.lta)
endif
echo ""
echo $cmd
$cmd
set diff_status=$status
if ($diff_status != 0) then
  echo "$cmd FAILED (exit status=$diff_status)"
  exit 1
endif

